import {
  TbArrowBigDown,
  TbArrowBigLeft,
  TbArrowBigRight,
  TbArrowBigUp,
  TbBrackets,
  TbCapsuleHorizontal,
  TbChartPie,
  TbCircle,
  TbCircleDot,
  TbCursorText,
  TbDiamond,
  TbHeading,
  TbHeart,
  TbIcons,
  TbImageInPicture,
  TbLine,
  TbRectangle,
  TbSquareDot,
  TbSquareRotated,
  TbStar,
  TbTable,
  TbTriangle,
} from 'react-icons/tb';
import PropTypes from 'prop-types';
import { FaArrowsUpDown } from 'react-icons/fa6';

export const icons = {
  heading: TbHeading,
  text: TbCursorText,
  chart: TbChartPie,
  logo: TbCapsuleHorizontal,
  circle: TbCircle,
  rectangle: TbRectangle,
  triangle: TbTriangle,
  'diagonal-rectangle': TbSquareRotated,
  'arrow-up': TbArrowBigUp,
  'arrow-right': TbArrowBigRight,
  'arrow-down': TbArrowBigDown,
  'arrow-left': TbArrowBigLeft,
  'arrow-up-down': FaArrowsUpDown,
  image: TbImageInPicture,
  table: TbTable,
  'key-value': TbBrackets,
  line: TbLine,
  'frame-rectangle': TbSquareDot,
  'frame-triangle': TbTriangle,
  'frame-circle': TbCircleDot,
  'frame-star': TbStar,
  'frame-heart': TbHeart,
  'frame-diamond': TbDiamond,
  icon: TbIcons,
};

const elements = [
  {
    id: 'heading',
    type: 'heading',
    name: 'Heading',
    icon: icons['heading'],
    data: {
      type: 'heading',
      text: 'Heading',
      width: 400,
      height: 36,
      style: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#000000',
        textAlign: 'left',
        opacity: 1,
        fontFamily: 'Roboto',
        letterSpacing: 0,
        lineHeight: 1,
        verticalAlign: 'baseline',
      },
    },
    tools: ['bold', 'italic', 'underline', 'font', 'text-color', 'opacity'],
    group: 'text',
    preview: (
      <h1
        style={{
          fontSize: '28px',
          fontWeight: 'bold',
          textAlign: 'left',
          opacity: 1,
          fontFamily: 'Roboto',
          letterSpacing: 0,
          lineHeight: 1,
          verticalAlign: 'baseline',
        }}
      >
        Heading
      </h1>
    ),
  },
  {
    id: 'text',
    type: 'text',
    name: 'Text',
    icon: icons['text'],
    data: {
      type: 'text',
      text: 'Text',
      width: 300,
      height: 20,
      style: {
        fontSize: 16,
        fontWeight: 'normal',
        color: '#000000',
        textAlign: 'left',
        opacity: 1,
        fontFamily: 'Roboto',
        letterSpacing: 0,
        lineHeight: 1,
        verticalAlign: 'baseline',
      },
    },
    tools: ['bold', 'italic', 'underline', 'font', 'text-color', 'text-align', 'opacity'],
    group: 'text',
    preview: (
      <p
        style={{
          fontSize: '16px',
          fontWeight: 'normal',
          textAlign: 'left',
          opacity: 1,
          fontFamily: 'Roboto',
          letterSpacing: 0,
          lineHeight: 1,
          verticalAlign: 'baseline',
        }}
      >
        Paragraph
      </p>
    ),
  },
  {
    id: 'text',
    type: 'text',
    name: 'Text',
    icon: icons['text'],
    data: {
      type: 'text',
      text: 'Text',
      width: 200,
      height: 12,
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        color: '#000000',
        textAlign: 'left',
        opacity: 1,
        fontFamily: 'Roboto',
        letterSpacing: 0,
        lineHeight: 1,
        verticalAlign: 'baseline',
      },
    },
    tools: ['bold', 'italic', 'underline', 'font', 'text-color', 'text-align', 'opacity'],
    group: 'text',
    preview: (
      <p
        style={{
          fontSize: '10px',
          fontWeight: 'normal',
          textAlign: 'left',
          opacity: 1,
          fontFamily: 'Roboto',
          letterSpacing: 0,
          lineHeight: 1,
          verticalAlign: 'baseline',
        }}
      >
        Sub Paragraph
      </p>
    ),
  },
  {
    id: 'chart',
    type: 'chart',
    name: 'Chart',
    icon: icons['chart'],
    data: {
      type: 'chart',
      text: 'Chart',
      width: 400,
      height: 400,
      style: { opacity: 1 },
    },
    tools: ['chart', 'opacity'],
    group: 'visual',
  },
  {
    id: 'table',
    type: 'table',
    name: 'Table',
    icon: icons['table'],
    data: {
      type: 'table',
      text: 'Table',
      width: 400,
      height: 200,
      style: {
        fontSize: 14,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#888',
        color: '#000',
        opacity: 1,
      },
    },
    tools: ['table', 'opacity', 'font', 'text-color', 'border', 'background-color'],
    group: 'visual',
  },
  {
    id: 'key-value',
    type: 'key-value',
    name: 'Key Value',
    icon: icons['key-value'],
    data: {
      type: 'key-value',
      text: 'Key Value',
      width: 400,
      height: 200,
      style: {
        fontSize: 14,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#888',
        color: '#000',
        opacity: 1,
      },
    },
    tools: ['key-value', 'opacity', 'font', 'text-color', 'border', 'background-color'],
    group: 'visual',
  },
  {
    id: 'logo',
    type: 'logo',
    name: 'Logo',
    icon: icons['logo'],
    data: {
      type: 'logo',
      text: 'Logo',
      width: 120,
      height: 0,
      style: { opacity: 1 },
    },
    tools: ['opacity'],
    group: 'visual',
  },
  {
    id: 'circle',
    type: 'circle',
    name: 'Circle',
    icon: icons['circle'],
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
      },
      type: 'circle',
      text: 'Circle',
      width: 120,
      height: 120,
    },
    tools: ['background-color', 'border', 'opacity'],
    group: 'shape',
  },
  {
    id: 'rectangle',
    type: 'rectangle',
    name: 'Rectangle',
    icon: icons['rectangle'],
    data: {
      style: {
        backgroundColor: '#ccc',
        rotate: '30',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
      },
      type: 'rectangle',
      text: 'Rectangle',
      width: 100,
      height: 100,
    },
    tools: ['background-color', 'border', 'opacity', 'border-radius'],
    group: 'shape',
  },
  {
    id: 'triangle',
    type: 'triangle',
    name: 'Triangle',
    icon: icons['triangle'],
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'triangle',
      text: 'Triangle',
      width: 200,
      height: 200,
    },
    tools: ['background-color', 'opacity'],
    group: 'shape',
  },
  {
    id: 'diagonal-rectangle',
    type: 'diagonal-rectangle',
    name: 'Diagonal Rectangle',
    icon: icons['diagonal-rectangle'],
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'diagonal-rectangle',
      text: 'Diagonal Rectangle',
      width: 200,
      height: 200,
    },
    tools: ['background-color', 'opacity'],
    group: 'shape',
  },
  {
    id: 'arrow-up',
    type: 'arrow-up',
    name: 'Arrow Up',
    icon: icons['arrow-up'],
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'arrow-up',
      text: 'Arrow Up',
      width: 200,
      height: 200,
    },
    tools: ['background-color', 'opacity'],
    group: 'shape',
  },
  {
    id: 'arrow-right',
    type: 'arrow-right',
    name: 'Arrow Right',
    icon: icons['arrow-right'],
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'arrow-right',
      text: 'Arrow Right',
      width: 200,
      height: 200,
    },
    tools: ['background-color', 'opacity'],
    group: 'shape',
  },
  {
    id: 'arrow-down',
    type: 'arrow-down',
    name: 'Arrow Down',
    icon: icons['arrow-down'],
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'arrow-down',
      text: 'Arrow Down',
      width: 200,
      height: 200,
    },
    tools: ['background-color', 'opacity'],
    group: 'shape',
  },
  {
    id: 'arrow-left',
    type: 'arrow-left',
    name: 'Arrow Left',
    icon: icons['arrow-left'],
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'arrow-left',
      text: 'Arrow Left',
      width: 200,
      height: 200,
    },
    tools: ['background-color', 'opacity'],
    group: 'shape',
  },
  {
    id: 'arrow-up-down',
    type: 'arrow-up-down',
    name: 'Arrow UpDown',
    icon: icons['arrow-up-down'],
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'arrow-up-down',
      text: 'Arrow UpDown',
      width: 200,
      height: 200,
    },
    tools: ['background-color', 'opacity'],
    group: 'shape',
  },
  {
    id: 'line',
    type: 'line',
    name: 'Line',
    icon: icons['line'],
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
        strokeWidth: 2,
      },
      lineEnd: null,
      lineStart: null,
      type: 'line',
      text: 'Line',
      width: 100,
      height: 4,
    },
    tools: ['background-color', 'opacity', 'line'],
    group: 'shape',
  },
  {
    id: 'frame-rectangle',
    type: 'frame-rectangle',
    name: 'Frame',
    icon: icons['frame-rectangle'],
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
      },
      type: 'frame-rectangle',
      text: 'Frame',
      width: 300,
      height: 300,
      children: [],
    },
    tools: ['opacity', 'border-radius'],
    group: 'frame',
  },
  {
    id: 'frame-triangle',
    type: 'frame-triangle',
    name: 'Triangle Frame',
    icon: icons['frame-triangle'],
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
      },
      type: 'frame-triangle',
      text: 'Frame',
      width: 300,
      height: 300,
      children: [],
    },
    tools: ['opacity'],
    group: 'frame',
  },
  {
    id: 'frame-circle',
    type: 'frame-circle',
    name: 'Circle Frame',
    icon: icons['frame-circle'],
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
      },
      type: 'frame-circle',
      text: 'Frame',
      width: 300,
      height: 300,
      children: [],
    },
    tools: ['opacity'],
    group: 'frame',
  },
  {
    id: 'frame-star',
    type: 'frame-star',
    name: 'Star Frame',
    icon: icons['frame-star'],
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
      },
      type: 'frame-star',
      text: 'Frame',
      width: 300,
      height: 300,
      children: [],
    },
    tools: ['opacity'],
    group: 'frame',
  },
  {
    id: 'frame-heart',
    type: 'frame-heart',
    name: 'Heart Frame',
    icon: icons['frame-heart'],
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
      },
      type: 'frame-heart',
      text: 'Frame',
      width: 300,
      height: 300,
      children: [],
    },
    tools: ['opacity'],
    group: 'frame',
  },
  {
    id: 'frame-diamond',
    type: 'frame-diamond',
    name: 'Diamond Frame',
    icon: icons['frame-diamond'],
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
      },
      type: 'frame-diamond',
      text: 'Frame',
      width: 300,
      height: 300,
      children: [],
    },
    tools: ['opacity'],
    group: 'frame',
  },
  {
    id: 'icon',
    type: 'icon',
    name: 'Icon',
    icon: icons['icon'],
    data: {
      type: 'icon',
      text: 'Icon',
      width: 60,
      height: 60,
      style: { opacity: 1 },
    },
    tools: ['icon', 'opacity'],
    group: 'placeholders',
  },
];

export default elements;

export const elementPropTypes = {
  element: PropTypes.shape({
    id: PropTypes.string.isRequired,
    type: PropTypes.string.isRequired,
    x: PropTypes.number.isRequired,
    y: PropTypes.number.isRequired,
    text: PropTypes.string.isRequired,
    width: PropTypes.number.isRequired,
    height: PropTypes.number.isRequired,
    style: PropTypes.object,
    src: PropTypes.string,
    config: PropTypes.object,
  }),
  active: PropTypes.bool.isRequired,
  highlighted: PropTypes.bool,
  onClick: PropTypes.func.isRequired,
  onChange: PropTypes.func.isRequired,
  width: PropTypes.number,
};

export const getElementTools = (id) => {
  const element = elements.find((el) => el.id === id);
  if (!element) throw new Error(`Element with id ${id} not found`);
  return element?.tools || [];
};
