import {
  TbArrowBigDown,
  TbArrowBigLeft,
  TbArrowBigRight,
  TbArrowBigUp,
  TbBrackets,
  TbCapsuleHorizontal,
  TbChartBar,
  TbChartLine,
  TbChartPie,
  TbCircle,
  TbCircleDot,
  TbCursorText,
  TbDiamond,
  TbHeading,
  TbHeart,
  TbIcons,
  TbImageInPicture,
  TbLine,
  TbRectangle,
  TbSquareDot,
  TbSquareRotated,
  TbStar,
  TbTable,
  TbTriangle,
} from 'react-icons/tb';
import PropTypes from 'prop-types';
import { FaArrowsUpDown } from 'react-icons/fa6';

const elements = [
  {
    id: 'heading',
    type: 'heading',
    name: 'Heading',
    data: {
      type: 'heading',
      text: 'Heading',
      width: 400,
      height: 36,
      style: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#000000',
        textAlign: 'left',
        opacity: 1,
        fontFamily: 'Roboto',
        letterSpacing: 0,
        lineHeight: 1,
        verticalAlign: 'baseline',
      },
    },
    group: 'text',
    category: 'design',
    preview: (
      <h1
        style={{
          fontSize: '28px',
          fontWeight: 'bold',
          textAlign: 'left',
          opacity: 1,
          fontFamily: 'Roboto',
          letterSpacing: 0,
          lineHeight: 1,
          verticalAlign: 'baseline',
        }}
      >
        Heading
      </h1>
    ),
  },
  {
    id: 'text',
    type: 'text',
    name: 'Text',
    data: {
      type: 'text',
      text: 'Text',
      width: 300,
      height: 20,
      style: {
        fontSize: 16,
        fontWeight: 'normal',
        color: '#000000',
        textAlign: 'left',
        opacity: 1,
        fontFamily: 'Roboto',
        letterSpacing: 0,
        lineHeight: 1,
        verticalAlign: 'baseline',
      },
    },
    group: 'text',
    category: 'design',
    preview: (
      <p
        style={{
          fontSize: '16px',
          fontWeight: 'normal',
          textAlign: 'left',
          opacity: 1,
          fontFamily: 'Roboto',
          letterSpacing: 0,
          lineHeight: 1,
          verticalAlign: 'baseline',
        }}
      >
        Paragraph
      </p>
    ),
  },
  {
    id: 'table',
    type: 'table',
    name: 'Table',
    data: {
      type: 'table',
      text: 'Table',
      width: 400,
      height: 200,
      style: {
        fontSize: 14,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#888',
        color: '#000',
        opacity: 1,
      },
    },
    group: 'visual',
    category: 'data',
  },
  {
    id: 'key-value',
    type: 'key-value',
    name: 'Key Value',
    data: {
      type: 'key-value',
      text: 'Key Value',
      width: 400,
      height: 200,
      style: {
        fontSize: 14,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#888',
        color: '#000',
        opacity: 1,
      },
    },
    group: 'visual',
    category: 'data',
  },
  {
    id: 'logo',
    type: 'logo',
    name: 'Logo',
    data: {
      type: 'logo',
      text: 'Logo',
      width: 120,
      height: 0,
      style: { opacity: 1 },
    },
    group: 'visual',
    category: 'design',
  },
  {
    id: 'circle',
    type: 'circle',
    name: 'Circle',
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
      },
      type: 'circle',
      text: 'Circle',
      width: 120,
      height: 120,
    },
    group: 'shape',
    category: 'design',
  },
  {
    id: 'rectangle',
    type: 'rectangle',
    name: 'Rectangle',
    data: {
      style: {
        backgroundColor: '#ccc',
        rotate: '30',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
      },
      type: 'rectangle',
      text: 'Rectangle',
      width: 100,
      height: 100,
    },
    group: 'shape',
    category: 'design',
  },
  {
    id: 'triangle',
    type: 'triangle',
    name: 'Triangle',
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'triangle',
      text: 'Triangle',
      width: 200,
      height: 200,
    },
    group: 'shape',
    category: 'design',
  },
  {
    id: 'diagonal-rectangle',
    type: 'diagonal-rectangle',
    name: 'Diagonal Rectangle',
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'diagonal-rectangle',
      text: 'Diagonal Rectangle',
      width: 200,
      height: 200,
    },
    group: 'shape',
    category: 'design',
  },
  {
    id: 'arrow-up',
    type: 'arrow-up',
    name: 'Arrow Up',
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'arrow-up',
      text: 'Arrow Up',
      width: 200,
      height: 200,
    },
    group: 'shape',
    category: 'design',
  },
  {
    id: 'arrow-right',
    type: 'arrow-right',
    name: 'Arrow Right',
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'arrow-right',
      text: 'Arrow Right',
      width: 200,
      height: 200,
    },
    group: 'shape',
    category: 'design',
  },
  {
    id: 'arrow-down',
    type: 'arrow-down',
    name: 'Arrow Down',
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'arrow-down',
      text: 'Arrow Down',
      width: 200,
      height: 200,
    },
    group: 'shape',
    category: 'design',
  },
  {
    id: 'arrow-left',
    type: 'arrow-left',
    name: 'Arrow Left',
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'arrow-left',
      text: 'Arrow Left',
      width: 200,
      height: 200,
    },
    group: 'shape',
    category: 'design',
  },
  {
    id: 'arrow-up-down',
    type: 'arrow-up-down',
    name: 'Arrow UpDown',
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'arrow-up-down',
      text: 'Arrow UpDown',
      width: 200,
      height: 200,
    },
    group: 'shape',
    category: 'design',
  },
  {
    id: 'line',
    type: 'line',
    name: 'Line',
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
        strokeWidth: 2,
      },
      lineEnd: null,
      lineStart: null,
      type: 'line',
      text: 'Line',
      width: 100,
      height: 4,
    },
    group: 'shape',
    category: 'design',
  },
  {
    id: 'frame-rectangle',
    type: 'frame-rectangle',
    name: 'Frame',
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
      },
      type: 'frame-rectangle',
      text: 'Frame',
      width: 300,
      height: 300,
      children: [],
    },
    group: 'frame',
    category: 'design',
  },
  {
    id: 'frame-triangle',
    type: 'frame-triangle',
    name: 'Triangle Frame',
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
      },
      type: 'frame-triangle',
      text: 'Frame',
      width: 300,
      height: 300,
      children: [],
    },
    group: 'frame',
    category: 'design',
  },
  {
    id: 'frame-circle',
    type: 'frame-circle',
    name: 'Circle Frame',
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
      },
      type: 'frame-circle',
      text: 'Frame',
      width: 300,
      height: 300,
      children: [],
    },
    group: 'frame',
    category: 'design',
  },
  {
    id: 'frame-star',
    type: 'frame-star',
    name: 'Star Frame',
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
      },
      type: 'frame-star',
      text: 'Frame',
      width: 300,
      height: 300,
      children: [],
    },
    group: 'frame',
    category: 'design',
  },
  {
    id: 'frame-heart',
    type: 'frame-heart',
    name: 'Heart Frame',
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
      },
      type: 'frame-heart',
      text: 'Frame',
      width: 300,
      height: 300,
      children: [],
    },
    group: 'frame',
    category: 'design',
  },
  {
    id: 'frame-diamond',
    type: 'frame-diamond',
    name: 'Diamond Frame',
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
      },
      type: 'frame-diamond',
      text: 'Frame',
      width: 300,
      height: 300,
      children: [],
    },
    group: 'frame',
    category: 'design',
  },
  {
    id: 'icon',
    type: 'icon',
    name: 'Icon',
    data: {
      type: 'icon',
      text: 'Icon',
      width: 60,
      height: 60,
      style: { opacity: 1 },
    },
    group: 'placeholders',
    category: 'design',
  },
];

export default {
  design: elements.filter((el) => el.category === 'design'),
  data: elements.filter((el) => el.category === 'data'),
};

export const icons = {
  heading: TbHeading,
  text: TbCursorText,
  logo: TbCapsuleHorizontal,
  circle: TbCircle,
  rectangle: TbRectangle,
  triangle: TbTriangle,
  'diagonal-rectangle': TbSquareRotated,
  'arrow-up': TbArrowBigUp,
  'arrow-right': TbArrowBigRight,
  'arrow-down': TbArrowBigDown,
  'arrow-left': TbArrowBigLeft,
  'arrow-up-down': FaArrowsUpDown,
  image: TbImageInPicture,
  table: TbTable,
  'key-value': TbBrackets,
  line: TbLine,
  'frame-rectangle': TbSquareDot,
  'frame-triangle': TbTriangle,
  'frame-circle': TbCircleDot,
  'frame-star': TbStar,
  'frame-heart': TbHeart,
  'frame-diamond': TbDiamond,
  icon: TbIcons,
  'chart-bar': TbChartBar,
  'chart-line': TbChartLine,
  'chart-pie': TbChartPie,
};

export const tools = {
  heading: ['bold', 'italic', 'underline', 'font', 'text-color', 'opacity'],
  text: ['bold', 'italic', 'underline', 'font', 'text-color', 'text-align', 'opacity'],
  table: ['table', 'opacity', 'font', 'text-color', 'border', 'background-color'],
  'key-value': ['key-value', 'opacity', 'font', 'text-color', 'border', 'background-color'],
  logo: ['opacity'],
  circle: ['background-color', 'border', 'opacity'],
  rectangle: ['background-color', 'border', 'opacity', 'border-radius'],
  triangle: ['background-color', 'opacity'],
  'diagonal-rectangle': ['background-color', 'opacity'],
  'arrow-up': ['background-color', 'opacity'],
  'arrow-right': ['background-color', 'opacity'],
  'arrow-down': ['background-color', 'opacity'],
  'arrow-left': ['background-color', 'opacity'],
  'arrow-up-down': ['background-color', 'opacity'],
  image: ['border', 'border-radius', 'opacity'],
  line: ['background-color', 'opacity', 'line'],
  'frame-rectangle': ['opacity', 'border-radius'],
  'frame-triangle': ['opacity'],
  'frame-circle': ['opacity'],
  'frame-star': ['opacity'],
  'frame-heart': ['opacity'],
  'frame-diamond': ['opacity'],
  icon: ['icon', 'opacity'],
  chart: ['chart', 'opacity'],
  'chart-bar': ['chart', 'opacity'],
  'chart-line': ['chart', 'opacity'],
  'chart-pie': ['chart', 'opacity'],
};

export const elementPropTypes = {
  element: PropTypes.shape({
    id: PropTypes.string.isRequired,
    type: PropTypes.string.isRequired,
    x: PropTypes.number.isRequired,
    y: PropTypes.number.isRequired,
    text: PropTypes.string.isRequired,
    width: PropTypes.number.isRequired,
    height: PropTypes.number.isRequired,
    style: PropTypes.object,
    src: PropTypes.string,
    config: PropTypes.object,
  }),
  active: PropTypes.bool.isRequired,
  highlighted: PropTypes.bool,
  onClick: PropTypes.func.isRequired,
  onChange: PropTypes.func.isRequired,
  width: PropTypes.number,
};

export const getElementTools = (type) => {
  if (!tools[type]) throw new Error(`No tools found for type ${type}`);
  return tools[type];
};

export const getElementIcon = (type) => {
  if (!icons[type]) throw new Error(`No icon found for type ${type}`);
  return icons[type];
};
