import { FaArrowsAltV } from 'react-icons/fa';
import {
  TbArrowBigDownFilled,
  TbArrowBigLeftFilled,
  TbArrowBigRightFilled,
  TbArrowBigUpFilled,
  TbCapsuleHorizontalFilled,
  TbChartPieFilled,
  TbCircleFilled,
  TbCursorText,
  TbHeading,
  TbRectangleFilled,
  TbSquareRotatedFilled,
  TbTriangleFilled,
} from 'react-icons/tb';

const elements = [
  {
    id: 'heading',
    type: 'heading',
    name: 'Heading',
    icon: TbHeading,
    data: {
      type: 'heading',
      text: 'Heading',
      width: 400,
      height: 36,
      style: { fontSize: 28, fontWeight: 'bold', color: '#000000' },
      tools: ['bold', 'italic', 'underline', 'font-size', 'text-color'],
    },
    group: 'text',
  },
  {
    id: 'text',
    type: 'text',
    name: 'Text',
    icon: TbCursorText,
    data: {
      type: 'text',
      text: 'Text',
      width: 300,
      height: 20,
      style: { fontSize: 16, fontWeight: 'normal', color: '#000000' },
      tools: ['bold', 'italic', 'underline', 'font-size', 'text-color'],
    },
    group: 'text',
  },
  {
    id: 'chart',
    type: 'chart',
    name: 'Chart',
    icon: TbChartPieFilled,
    data: {
      type: 'chart',
      text: 'Chart',
      width: 400,
      height: 400,
      tools: ['chart-picker'],
    },
    group: 'visual',
  },
  {
    id: 'logo',
    type: 'logo',
    name: 'Logo',
    icon: TbCapsuleHorizontalFilled,
    data: { type: 'logo', text: 'Logo', width: 120, height: 0 },
    group: 'visual',
  },
  {
    id: 'circle',
    type: 'circle',
    name: 'Circle',
    icon: TbCircleFilled,
    data: {
      style: { backgroundColor: '#ccc' },
      type: 'circle',
      text: 'Circle',
      width: 120,
      height: 120,
      tools: ['background-color'],
    },
    group: 'shape',
  },
  {
    id: 'rectangle',
    type: 'rectangle',
    name: 'Rectangle',
    icon: TbRectangleFilled,
    data: {
      style: { backgroundColor: '#ccc', rotate: '30' },
      type: 'rectangle',
      text: 'Rectangle',
      width: 100,
      height: 100,
      tools: ['background-color'],
    },
    group: 'shape',
  },
  {
    id: 'triangle',
    type: 'triangle',
    name: 'Triangle',
    icon: TbTriangleFilled,
    data: {
      style: { backgroundColor: '#ccc' },
      type: 'triangle',
      text: 'Triangle',
      width: 200,
      height: 200,
      tools: ['background-color'],
    },
    group: 'shape',
  },
  {
    id: 'diagonal-rectangle',
    type: 'diagonal-rectangle',
    name: 'Diagonal Rectangle',
    icon: TbSquareRotatedFilled,
    data: {
      style: { backgroundColor: '#ccc' },
      type: 'diagonal-rectangle',
      text: 'Diagonal Rectangle',
      width: 200,
      height: 200,
      tools: ['background-color'],
    },
    group: 'shape',
  },
  {
    id: 'arrow-up',
    type: 'arrow-up',
    name: 'Arrow Up',
    icon: TbArrowBigUpFilled,
    data: {
      style: { backgroundColor: '#ccc' },
      type: 'arrow-up',
      text: 'Arrow Up',
      width: 200,
      height: 200,
      tools: ['background-color'],
    },
    group: 'shape',
  },
  {
    id: 'arrow-right',
    type: 'arrow-right',
    name: 'Arrow Right',
    icon: TbArrowBigRightFilled,
    data: {
      style: { backgroundColor: '#ccc' },
      type: 'arrow-right',
      text: 'Arrow Right',
      width: 200,
      height: 200,
      tools: ['background-color'],
    },
    group: 'shape',
  },
  {
    id: 'arrow-down',
    type: 'arrow-down',
    name: 'Arrow Down',
    icon: TbArrowBigDownFilled,
    data: {
      style: { backgroundColor: '#ccc' },
      type: 'arrow-down',
      text: 'Arrow Down',
      width: 200,
      height: 200,
      tools: ['background-color'],
    },
    group: 'shape',
  },
  {
    id: 'arrow-left',
    type: 'arrow-left',
    name: 'Arrow Left',
    icon: TbArrowBigLeftFilled,
    data: {
      style: { backgroundColor: '#ccc' },
      type: 'arrow-left',
      text: 'Arrow Left',
      width: 200,
      height: 200,
      tools: ['background-color'],
    },
    group: 'shape',
  },
  {
    id: 'arrow-up-down',
    type: 'arrow-up-down',
    name: 'Arrow UpDown',
    icon: FaArrowsAltV,
    data: {
      style: { backgroundColor: '#ccc' },
      type: 'arrow-up-down',
      text: 'Arrow UpDown',
      width: 200,
      height: 200,
      tools: ['background-color'],
    },
    group: 'shape',
  },
];

export default elements;
