import {
  TbArrowBigDownFilled,
  TbArrowBigLeftFilled,
  TbArrowBigRightFilled,
  TbArrowBigUpFilled,
  TbBrackets,
  TbCapsuleHorizontalFilled,
  TbCarouselHorizontalFilled,
  TbChartAreaLine,
  TbChartBar,
  TbChartDonut4,
  TbChartLine,
  TbChartPieFilled,
  TbCircleFilled,
  TbCursorText,
  TbHeading,
  TbHeartFilled,
  TbIcons,
  TbImageInPicture,
  TbLine,
  TbRectangleFilled,
  TbSquareRotatedFilled,
  TbStarFilled,
  TbTableFilled,
  TbTriangleFilled,
  TbPentagonFilled,
  TbHexagonFilled,
  TbOctagonFilled,
  TbJewishStarFilled,
  TbCrossFilled,
  TbArrowBadgeLeftFilled,
  TbRectangleVerticalFilled,
} from 'react-icons/tb';
import { FaArrowsUpDown } from 'react-icons/fa6';
import { PiParallelogramFill, PiStarFourFill, PiTagChevronFill } from 'react-icons/pi';
import { RiBarChart2Line, RiBarChartHorizontalFill, RiCheckboxMultipleBlankFill, RiTicketFill } from 'react-icons/ri';
import { BsHeptagonFill } from "react-icons/bs";
import { ImCross } from "react-icons/im";
import { BiSolidMessageAlt } from "react-icons/bi";
import { IoBookmarkSharp } from "react-icons/io5";
import Heading from '@/components/core/templates/create/elements/texts/Heading.jsx';
import Text from '@/components/core/templates/create/elements/texts/Text.jsx';
import Logo from '@/components/core/templates/create/elements/Logo.jsx';
import Image from '@/components/core/templates/create/elements/Image.jsx';
import Table from '@/components/core/templates/create/elements/Table.jsx';
import KeyValue from '@/components/core/templates/create/elements/KeyValue.jsx';
import Line from '@/components/core/templates/create/elements/Line.jsx';
import SsIcon from '@/components/core/templates/create/elements/SsIcon.jsx';
import StandardBarChart from '@/components/core/templates/create/elements/charts/StandardBarChart.jsx';
import StandardLineChart from '@/components/core/templates/create/elements/charts/StandardLineChart.jsx';
import StandardPieChart from '@/components/core/templates/create/elements/charts/StandardPieChart.jsx';
import GenericShape from '@/components/core/templates/create/elements/shapes/GenericShape.jsx';
import GenericFrameShape from '@/components/core/templates/create/elements/frames/GenericFrameShape.jsx';
import StandardDoughnutChart from '@/components/core/templates/create/elements/charts/StandardDoughnutChart.jsx';
import StandardBarChartHorizontal from '@/components/core/templates/create/elements/charts/StandardBarChartHorizontal.jsx';
import StandardAreaChart from '@/components/core/templates/create/elements/charts/StandardAreaChart.jsx';
import AdvancedCharts from '@/components/core/templates/create/elements/charts/advanced/AdvancedCharts.jsx';
import FrameTabs from '@/components/core/templates/create/elements/frames/FrameTabs.jsx';
import FrameCarousel from '@/components/core/templates/create/elements/frames/FrameCarousel.jsx';
import StandardStackedBar from '@/components/core/templates/create/elements/charts/StandardStackedBar';


export const icons = {
  heading: TbHeading,
  text: TbCursorText,
  'shape-rectangle': TbRectangleFilled,
  'shape-circle': TbCircleFilled,
  'shape-triangle': TbTriangleFilled,
  'shape-rhombus': TbSquareRotatedFilled,
  'shape-arrow-up': TbArrowBigUpFilled,
  'shape-arrow-right': TbArrowBigRightFilled,
  'shape-arrow-down': TbArrowBigDownFilled,
  'shape-arrow-left': TbArrowBigLeftFilled,
  'shape-arrow-up-down': FaArrowsUpDown,
  'shape-four-pointed-star': PiStarFourFill,
  'shape-five-pointed-star': TbStarFilled,
  'shape-six-pointed-star': TbJewishStarFilled,
  'shape-eight-pointed-star': TbJewishStarFilled,
  'shape-parallelogram': PiParallelogramFill,
  'shape-trapeziod': PiParallelogramFill,
  'shape-pentagon': TbPentagonFilled,
  'shape-hexagon': TbHexagonFilled,
  'shape-heptagon': BsHeptagonFill,
  'shape-octagon': TbOctagonFilled,
  'shape-chevron-left': TbArrowBadgeLeftFilled,
  'shape-chevron-right': PiTagChevronFill,
  'shape-close': ImCross,
  'shape-message': BiSolidMessageAlt,
  'shape-cross': TbCrossFilled,
  'shape-book-mark': IoBookmarkSharp,
  'shape-arrow-concave': RiTicketFill,
  'shape-rabbet': TbRectangleVerticalFilled,
  'frame-rectangle': TbRectangleFilled,
  'frame-triangle': TbTriangleFilled,
  'frame-circle': TbCircleFilled,
  'frame-heart': TbHeartFilled,
  'frame-rhombus': TbSquareRotatedFilled,
  'frame-arrow-left': TbArrowBigLeftFilled,
  'frame-arrow-right': TbArrowBigRightFilled,
  'frame-arrow-up': TbArrowBigUpFilled,
  'frame-arrow-down': TbArrowBigDownFilled,
  'frame-arrow-up-down': FaArrowsUpDown,
  'frame-four-pointed-star': PiStarFourFill,
  'frame-five-pointed-star': TbStarFilled,
  'frame-six-pointed-star': TbJewishStarFilled,
  'frame-eight-pointed-star': TbJewishStarFilled,
  'frame-parallelogram': PiParallelogramFill,
  'frame-trapeziod': PiParallelogramFill,
  'frame-pentagon': TbPentagonFilled,
  'frame-hexagon': TbHexagonFilled,
  'frame-heptagon': BsHeptagonFill,
  'frame-octagon': TbOctagonFilled,
  'frame-chevron-left': TbArrowBadgeLeftFilled,
  'frame-chevron-right': PiTagChevronFill,
  'frame-close': ImCross,
  'frame-message': BiSolidMessageAlt,
  'frame-cross': TbCrossFilled,
  'frame-book-mark': IoBookmarkSharp,
  'frame-arrow-concave': RiTicketFill,
  'frame-rabbet': TbRectangleVerticalFilled,
  'frame-tabs': RiCheckboxMultipleBlankFill,
  'frame-carousel': TbCarouselHorizontalFilled,
  logo: TbCapsuleHorizontalFilled,
  line: TbLine,
  image: TbImageInPicture,
  table: TbTableFilled,
  'key-value': TbBrackets,
  icon: TbIcons,
  'chart-bar': TbChartBar,
  'chart-line': TbChartLine,
  'chart-pie': TbChartPieFilled,
  'chart-10-shapes': TbCapsuleHorizontalFilled,
  'chart-10-square': TbCapsuleHorizontalFilled,
  'chart-doughnut': TbChartDonut4,
  'chart-bar-horizontal': RiBarChartHorizontalFill,
  'chart-area': TbChartAreaLine,
  'chart-stacked-bar': RiBarChart2Line,
};

export const tools = {
  heading: ['bold', 'italic', 'underline', 'font', 'text-color', 'opacity', 'animation', 'shadow'],
  text: ['bold', 'italic', 'underline', 'font', 'text-color', 'text-align', 'opacity', 'animation', 'shadow'],
  'shape-rectangle': ['background-color', 'border', 'opacity', 'border-radius', 'animation', 'shadow'],
  'shape-circle': ['background-color', 'border', 'opacity', 'animation', 'shadow'],
  'shape-triangle': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-rhombus': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-arrow-up': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-arrow-right': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-arrow-down': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-arrow-left': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-arrow-up-down': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-four-pointed-star': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-five-pointed-star': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-six-pointed-star': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-eight-pointed-star': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-parallelogram': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-trapeziod': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-pentagon': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-hexagon': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-heptagon': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-octagon': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-chevron-left': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-chevron-right': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-close': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-message': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-cross': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-book-mark': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-arrow-concave': ['background-color', 'opacity', 'animation', 'shadow'],
  'shape-rabbet': ['background-color', 'opacity', 'animation', 'shadow'],
  'frame-rectangle': ['opacity', 'border-radius', 'animation', 'shadow'],
  'frame-triangle': ['opacity', 'animation', 'shadow'],
  'frame-circle': ['opacity', 'animation', 'shadow'],
  'frame-star': ['opacity', 'animation', 'shadow'],
  'frame-heart': ['opacity', 'animation', 'shadow'],
  'frame-rhombus': ['opacity', 'animation', 'shadow'],
  'frame-arrow-left': ['opacity', 'animation', 'shadow'],
  'frame-arrow-right': ['opacity', 'animation', 'shadow'],
  'frame-arrow-up': ['opacity', 'animation', 'shadow'],
  'frame-arrow-down': ['opacity', 'animation', 'shadow'],
  'frame-arrow-up-down': ['opacity', 'animation', 'shadow'],
  'frame-tabs': ['opacity', 'animation', 'shadow'],
  'frame-carousel': ['opacity', 'animation', 'shadow'],
  'frame-four-pointed-star': ['opacity', 'animation', 'shadow'],
  'frame-five-pointed-star': ['opacity', 'animation', 'shadow'],
  'frame-six-pointed-star': ['opacity', 'animation', 'shadow'],
  'frame-eight-pointed-star': ['opacity', 'animation', 'shadow'],
  'frame-parallelogram': ['opacity', 'animation', 'shadow'],
  'frame-trapeziod': ['opacity', 'animation', 'shadow'],
  'frame-pentagon': ['opacity', 'animation', 'shadow'],
  'frame-hexagon': ['opacity', 'animation', 'shadow'],
  'frame-heptagon': ['opacity', 'animation', 'shadow'],
  'frame-octagon': ['opacity', 'animation', 'shadow'],
  'frame-chevron-left': ['opacity', 'animation', 'shadow'],
  'frame-chevron-right': ['opacity', 'animation', 'shadow'],
  'frame-close': ['opacity', 'animation', 'shadow'],
  'frame-message': ['opacity', 'animation', 'shadow'],
  'frame-cross': ['opacity', 'animation', 'shadow'],
  'frame-book-mark': ['opacity', 'animation', 'shadow'],
  'frame-arrow-concave': ['opacity', 'animation', 'shadow'],
  'frame-rabbet': ['opacity', 'animation', 'shadow'],
  logo: ['opacity', 'animation', 'shadow'],
  line: ['background-color', 'opacity', 'line', 'animation', 'shadow'],
  icon: ['icon', 'opacity', 'animation', 'shadow'],
  image: ['border', 'border-radius', 'opacity', 'animation', 'shadow'],
  table: ['table', 'opacity', 'font', 'text-color', 'border', 'background-color', 'animation'],
  'key-value': ['key-value', 'opacity', 'font', 'text-color', 'border', 'background-color', 'animation'],
  'chart-bar': ['chart', 'opacity', 'animation'],
  'chart-line': ['chart', 'opacity', 'animation'],
  'chart-pie': ['chart', 'opacity', 'animation'],
  'chart-doughnut': ['chart', 'opacity', 'animation'],
  'chart-10-shapes': ['advanced-chart', 'opacity'],
  'chart-10-square': ['advanced-chart', 'opacity'],
  'chart-bar-horizontal': ['chart', 'opacity'],
  'chart-area': ['chart', 'opacity'],
  'chart-stacked-bar': ['chart', 'opacity'],
};

export const components = {
  heading: Heading,
  text: Text,
  'shape-rectangle': GenericShape,
  'shape-circle': GenericShape,
  'shape-triangle': GenericShape,
  'shape-rhombus': GenericShape,
  'shape-arrow-up': GenericShape,
  'shape-arrow-down': GenericShape,
  'shape-arrow-right': GenericShape,
  'shape-arrow-left': GenericShape,
  'shape-arrow-up-down': GenericShape,
  'shape-four-pointed-star': GenericShape,
  'shape-five-pointed-star': GenericShape,
  'shape-six-pointed-star': GenericShape,
  'shape-eight-pointed-star': GenericShape,
  'shape-trapeziod': GenericShape,
  'shape-parallelogram': GenericShape,
  'shape-pentagon': GenericShape,
  'shape-hexagon': GenericShape,
  'shape-heptagon': GenericShape,
  'shape-octagon': GenericShape,
  'shape-chevron-left': GenericShape,
  'shape-chevron-right': GenericShape,
  'shape-close': GenericShape,
  'shape-message': GenericShape,
  'shape-cross': GenericShape,
  'shape-book-mark': GenericShape,
  'shape-arrow-concave': GenericShape,
  'shape-rabbet': GenericShape,
  'frame-rectangle': GenericFrameShape,
  'frame-triangle': GenericFrameShape,
  'frame-circle': GenericFrameShape,
  // 'frame-star': GenericFrameShape,
  'frame-heart': GenericFrameShape,
  'frame-rhombus': GenericFrameShape,
  'frame-arrow-left': GenericFrameShape,
  'frame-arrow-right': GenericFrameShape,
  'frame-arrow-up': GenericFrameShape,
  'frame-arrow-down': GenericFrameShape,
  'frame-arrow-up-down': GenericFrameShape,
  'frame-four-pointed-star': GenericFrameShape,
  'frame-five-pointed-star': GenericFrameShape,
  'frame-six-pointed-star': GenericFrameShape,
  'frame-eight-pointed-star': GenericFrameShape,
  'frame-parallelogram': GenericFrameShape,
  'frame-trapeziod': GenericFrameShape,
  'frame-pentagon': GenericFrameShape,
  'frame-hexagon': GenericFrameShape,
  'frame-heptagon': GenericFrameShape,
  'frame-octagon': GenericFrameShape,
  'frame-chevron-left': GenericFrameShape,
  'frame-chevron-right': GenericFrameShape,
  'frame-close': GenericFrameShape,
  'frame-message': GenericFrameShape,
  'frame-cross': GenericFrameShape,
  'frame-book-mark': GenericFrameShape,
  'frame-arrow-concave': GenericFrameShape,
  'frame-rabbet': GenericFrameShape,
  'frame-tabs': FrameTabs,
  'frame-carousel': FrameCarousel,
  logo: Logo,
  line: Line,
  image: Image,
  table: Table,
  'key-value': KeyValue,
  icon: SsIcon,
  'chart-bar': StandardBarChart,
  'chart-line': StandardLineChart,
  'chart-pie': StandardPieChart,
  'chart-10-shapes': AdvancedCharts,
  'chart-doughnut': StandardDoughnutChart,
  'chart-bar-horizontal': StandardBarChartHorizontal,
  'chart-area': StandardAreaChart,
  'chart-stacked-bar': StandardStackedBar,
};

export const getElementTools = (type) => {
  if (!tools[type]) throw new Error(`No tools found for type ${type}`);
  return tools[type];
};

export const getElementIcon = (type) => {
  if (!icons[type]) throw new Error(`No icon found for type ${type}`);
  return icons[type];
};
