import { FaArrowsAltV } from 'react-icons/fa';
import {
  TbArrowBigDownFilled,
  TbArrowBigLeftFilled,
  TbArrowBigRightFilled,
  TbArrowBigUpFilled,
  TbBrackets,
  TbCapsuleHorizontalFilled,
  TbChartPieFilled,
  TbCircleFilled,
  TbContainer,
  TbCursorText,
  TbHeading,
  TbImageInPicture,
  TbRectangleFilled,
  TbSquareRotatedFilled,
  TbTable,
  TbTriangleFilled,
} from 'react-icons/tb';
import { IoRemoveOutline } from 'react-icons/io5';
import PropTypes from 'prop-types';

export const icons = {
  heading: TbHeading,
  text: TbCursorText,
  chart: TbChartPieFilled,
  logo: TbCapsuleHorizontalFilled,
  circle: TbCircleFilled,
  rectangle: TbRectangleFilled,
  triangle: TbTriangleFilled,
  'diagonal-rectangle': TbSquareRotatedFilled,
  'arrow-up': TbArrowBigUpFilled,
  'arrow-right': TbArrowBigRightFilled,
  'arrow-down': TbArrowBigDownFilled,
  'arrow-left': TbArrowBigLeftFilled,
  'arrow-up-down': FaArrowsAltV,
  image: TbImageInPicture,
  table: TbTable,
  'key-value': TbBrackets,
  line: IoRemoveOutline,
  'frame-rectangle': TbContainer,
};

const elements = [
  {
    id: 'heading',
    type: 'heading',
    name: 'Heading',
    icon: icons['heading'],
    data: {
      type: 'heading',
      text: 'Heading',
      width: 400,
      height: 36,
      style: { fontSize: 28, fontWeight: 'bold', color: '#000000', textAlign: 'left', opacity: 1 },
      tools: ['bold', 'italic', 'underline', 'font-size', 'text-color', 'opacity'],
    },
    group: 'text',
  },
  {
    id: 'text',
    type: 'text',
    name: 'Text',
    icon: icons['text'],
    data: {
      type: 'text',
      text: 'Text',
      width: 300,
      height: 20,
      style: { fontSize: 16, fontWeight: 'normal', color: '#000000', textAlign: 'left', opacity: 1 },
      tools: ['bold', 'italic', 'underline', 'font-size', 'text-color', 'text-align', 'opacity'],
    },
    group: 'text',
  },
  {
    id: 'chart',
    type: 'chart',
    name: 'Chart',
    icon: icons['chart'],
    data: {
      type: 'chart',
      text: 'Chart',
      width: 400,
      height: 400,
      style: { opacity: 1 },
      tools: ['chart', 'opacity'],
    },
    group: 'visual',
  },
  {
    id: 'table',
    type: 'table',
    name: 'Table',
    icon: icons['table'],
    data: {
      type: 'table',
      text: 'Table',
      width: 400,
      height: 200,
      style: {
        fontSize: 14,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#888',
        color: '#000',
        opacity: 1,
      },
      tools: ['table', 'opacity', 'font-size', 'text-color', 'border', 'background-color'],
    },
    group: 'visual',
  },
  {
    id: 'key-value',
    type: 'key-value',
    name: 'Key Value',
    icon: icons['key-value'],
    data: {
      type: 'key-value',
      text: 'Key Value',
      width: 400,
      height: 200,
      style: {
        fontSize: 14,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#888',
        color: '#000',
        opacity: 1,
      },
      tools: ['key-value', 'opacity', 'font-size', 'text-color', 'border', 'background-color'],
    },
    group: 'visual',
  },
  {
    id: 'logo',
    type: 'logo',
    name: 'Logo',
    icon: icons['logo'],
    data: {
      type: 'logo',
      text: 'Logo',
      width: 120,
      height: 0,
      style: { opacity: 1 },
      tools: ['opacity'],
    },
    group: 'visual',
  },
  {
    id: 'circle',
    type: 'circle',
    name: 'Circle',
    icon: icons['circle'],
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
      },
      type: 'circle',
      text: 'Circle',
      width: 120,
      height: 120,
      tools: ['background-color', 'border', 'opacity'],
    },
    group: 'shape',
  },
  {
    id: 'rectangle',
    type: 'rectangle',
    name: 'Rectangle',
    icon: icons['rectangle'],
    data: {
      style: {
        backgroundColor: '#ccc',
        rotate: '30',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
      },
      type: 'rectangle',
      text: 'Rectangle',
      width: 100,
      height: 100,
      tools: ['background-color', 'border', 'opacity', 'border-radius'],
    },
    group: 'shape',
  },
  {
    id: 'triangle',
    type: 'triangle',
    name: 'Triangle',
    icon: icons['triangle'],
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'triangle',
      text: 'Triangle',
      width: 200,
      height: 200,
      tools: ['background-color', 'opacity'],
    },
    group: 'shape',
  },
  {
    id: 'diagonal-rectangle',
    type: 'diagonal-rectangle',
    name: 'Diagonal Rectangle',
    icon: icons['diagonal-rectangle'],
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'diagonal-rectangle',
      text: 'Diagonal Rectangle',
      width: 200,
      height: 200,
      tools: ['background-color', 'opacity'],
    },
    group: 'shape',
  },
  {
    id: 'arrow-up',
    type: 'arrow-up',
    name: 'Arrow Up',
    icon: icons['arrow-up'],
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'arrow-up',
      text: 'Arrow Up',
      width: 200,
      height: 200,
      tools: ['background-color', 'opacity'],
    },
    group: 'shape',
  },
  {
    id: 'arrow-right',
    type: 'arrow-right',
    name: 'Arrow Right',
    icon: icons['arrow-right'],
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'arrow-right',
      text: 'Arrow Right',
      width: 200,
      height: 200,
      tools: ['background-color', 'opacity'],
    },
    group: 'shape',
  },
  {
    id: 'arrow-down',
    type: 'arrow-down',
    name: 'Arrow Down',
    icon: icons['arrow-down'],
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'arrow-down',
      text: 'Arrow Down',
      width: 200,
      height: 200,
      tools: ['background-color', 'opacity'],
    },
    group: 'shape',
  },
  {
    id: 'arrow-left',
    type: 'arrow-left',
    name: 'Arrow Left',
    icon: icons['arrow-left'],
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'arrow-left',
      text: 'Arrow Left',
      width: 200,
      height: 200,
      tools: ['background-color', 'opacity'],
    },
    group: 'shape',
  },
  {
    id: 'arrow-up-down',
    type: 'arrow-up-down',
    name: 'Arrow UpDown',
    icon: icons['arrow-up-down'],
    data: {
      style: { backgroundColor: '#ccc', opacity: 1 },
      type: 'arrow-up-down',
      text: 'Arrow UpDown',
      width: 200,
      height: 200,
      tools: ['background-color', 'opacity'],
    },
    group: 'shape',
  },
  {
    id: 'line',
    type: 'line',
    name: 'Line',
    icon: icons['line'],
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
        strokeWidth: 2,
      },
      lineEnd: null,
      lineStart: null,
      type: 'line',
      text: 'Line',
      width: 100,
      height: 4,
      tools: ['background-color', 'opacity', 'line'],
    },
    group: 'shape',
  },
  {
    id: 'frame-rectangle',
    type: 'frame-rectangle',
    name: 'Frame',
    icon: icons['frame-rectangle'],
    data: {
      style: {
        backgroundColor: '#ccc',
        borderWidth: 0,
        borderColor: '#000000',
        opacity: 1,
        borderRadius: 0,
      },
      type: 'frame-rectangle',
      text: 'Frame',
      width: 300,
      height: 300,
      tools: ['opacity', 'border-radius'],
      children: [],
    },
    group: 'frame',
  },
];

export default elements;

export const elementPropTypes = {
  element: PropTypes.shape({
    id: PropTypes.string.isRequired,
    type: PropTypes.string.isRequired,
    x: PropTypes.number.isRequired,
    y: PropTypes.number.isRequired,
    text: PropTypes.string.isRequired,
    width: PropTypes.number.isRequired,
    height: PropTypes.number.isRequired,
    style: PropTypes.object,
    src: PropTypes.string,
    config: PropTypes.object,
  }),
  active: PropTypes.bool.isRequired,
  highlighted: PropTypes.bool,
  onClick: PropTypes.func.isRequired,
  onChange: PropTypes.func.isRequired,
  width: PropTypes.number,
};
