
export const tableData = [
    {
      id: 1,
      exchange: 'NGX ASI',
      rank: 2,
      threeWay: { 1: 4.7, X: 1.3, 2: 15.3 },
      overUnder: { goals: 2.5, over: 4.8, under: 6.7 },
      score: '12+',
    },
    {
      id: 2,
      exchange: 'NASDAQ',
      rank: 1,
      threeWay: { 1: 2.1, X: 5.1, 2: 8.2 },
      overUnder: { goals: 4.6, over: 1.5, under: 7.3 },
      score: '27+',
    },
    {
      id: 3,
      exchange: 'DAX',
      rank: 4,
      threeWay: { 1: 3.5, X: 1.2, 2: 10.3 },
      overUnder: { goals: 2.7, over: 3.6, under: 1.7 },
      score: '82+',
    },
    {
      id: 4,
      exchange: 'NGX ASI',
      rank: 3,
      threeWay: { 1: 1.3, X: 5.3, 2: 5.8 },
      overUnder: { goals: 3.5, over: 1.9, under: 8.6 },
      score: '65+',
    },
    {
      id: 5,
      exchange: 'NASDAQ',
      rank: 5,
      threeWay: { 1: 2.5, X: 7.1, 2: 8.3 },
      overUnder: { goals: 1.7, over: 5.2, under: 3.2 },
      score: '51+',
    },
    {
        id: 6,
        exchange: 'FTSE 100',
        rank: 6,
        threeWay: { 1: 3.2, X: 2.4, 2: 9.1 },
        overUnder: { goals: 2.9, over: 4.1, under: 5.2 },
        score: '43+',
      },
      {
        id: 7,
        exchange: 'S&P 500',
        rank: 7,
        threeWay: { 1: 4.5, X: 3.1, 2: 6.8 },
        overUnder: { goals: 1.8, over: 3.9, under: 6.1 },
        score: '19+',
      },
      {
        id: 8,
        exchange: 'HANG SENG',
        rank: 8,
        threeWay: { 1: 2.9, X: 1.5, 2: 7.2 },
        overUnder: { goals: 3.2, over: 2.5, under: 4.3 },
        score: '78+',
      },
      {
        id: 9,
        exchange: 'CAC 40',
        rank: 9,
        threeWay: { 1: 5.1, X: 2.7, 2: 8.6 },
        overUnder: { goals: 2.3, over: 1.8, under: 3.9 },
        score: '35+',
      },
      {
        id: 10,
        exchange: 'NIKKEI 225',
        rank: 10,
        threeWay: { 1: 3.8, X: 4.2, 2: 6.3 },
        overUnder: { goals: 1.5, over: 2.1, under: 4.6 },
        score: '90+',
      },
  ];

  export const equityData = [
    {
        id: 6,
        exchange: 'FTSE 100',
        rank: 6,
        threeWay: { 1: 3.2, X: 2.4, 2: 9.1 },
        overUnder: { goals: 2.9, over: 4.1, under: 5.2 },
        score: '43+',
      },
      {
        id: 7,
        exchange: 'S&P 500',
        rank: 7,
        threeWay: { 1: 4.5, X: 3.1, 2: 6.8 },
        overUnder: { goals: 1.8, over: 3.9, under: 6.1 },
        score: '19+',
      },
      {
        id: 8,
        exchange: 'HANG SENG',
        rank: 8,
        threeWay: { 1: 2.9, X: 1.5, 2: 7.2 },
        overUnder: { goals: 3.2, over: 2.5, under: 4.3 },
        score: '78+',
      },
      {
        id: 9,
        exchange: 'CAC 40',
        rank: 9,
        threeWay: { 1: 5.1, X: 2.7, 2: 8.6 },
        overUnder: { goals: 2.3, over: 1.8, under: 3.9 },
        score: '35+',
      },
      {
        id: 10,
        exchange: 'NIKKEI 225',
        rank: 10,
        threeWay: { 1: 3.8, X: 4.2, 2: 6.3 },
        overUnder: { goals: 1.5, over: 2.1, under: 4.6 },
        score: '90+',
      },
  ];