import {
  TbBattery,
  TbBell,
  TbBookmark,
  TbBriefcase,
  TbCalendar,
  TbCamera,
  TbCheck,
  TbCircle,
  TbClock,
  TbCloud,
  TbCreditCard,
  TbDownload,
  TbEdit,
  TbEye,
  TbEyeOff,
  TbFilter,
  TbFlag,
  TbHeart,
  TbHome,
  TbLink,
  TbLock,
  TbMail,
  TbMap,
  TbMenu,
  TbMicrophone,
  TbMinus,
  TbMoon,
  TbMusic,
  TbPhone,
  TbPlus,
  TbPrinter,
  TbRefresh,
  TbSearch,
  TbSettings,
  TbShare,
  TbShoppingCart,
  TbSquare,
  TbStar,
  TbSun,
  TbTag,
  TbTrash,
  TbTriangle,
  TbUmbrella,
  TbUpload,
  TbUser,
  TbVideo,
  TbVolume,
  TbWifi,
  TbX,
} from 'react-icons/tb';

export const iconTypes = [
  { name: 'heart', icon: TbHeart, keys: ['heart', 'love', 'like'], type: 'react-icons' },
  { name: 'user', icon: TbUser, keys: ['user', 'person', 'profile'], type: 'react-icons' },
  { name: 'home', icon: TbHome, keys: ['home', 'house', 'residence'], type: 'react-icons' },
  { name: 'search', icon: TbSearch, keys: ['search', 'find', 'magnify'], type: 'react-icons' },
  { name: 'settings', icon: TbSettings, keys: ['settings', 'gear', 'preferences'], type: 'react-icons' },
  { name: 'bell', icon: TbBell, keys: ['bell', 'notification', 'alert'], type: 'react-icons' },
  { name: 'mail', icon: TbMail, keys: ['mail', 'email', 'message'], type: 'react-icons' },
  { name: 'phone', icon: TbPhone, keys: ['phone', 'call', 'telephone'], type: 'react-icons' },
  { name: 'camera', icon: TbCamera, keys: ['camera', 'photo', 'picture'], type: 'react-icons' },
  { name: 'calendar', icon: TbCalendar, keys: ['calendar', 'date', 'schedule'], type: 'react-icons' },
  { name: 'clock', icon: TbClock, keys: ['clock', 'time', 'watch'], type: 'react-icons' },
  { name: 'map', icon: TbMap, keys: ['map', 'location', 'navigation'], type: 'react-icons' },
  { name: 'star', icon: TbStar, keys: ['star', 'favorite', 'rating'], type: 'react-icons' },
  { name: 'bookmark', icon: TbBookmark, keys: ['bookmark', 'save', 'favorite'], type: 'react-icons' },
  { name: 'trash', icon: TbTrash, keys: ['trash', 'delete', 'remove'], type: 'react-icons' },
  { name: 'edit', icon: TbEdit, keys: ['edit', 'pencil', 'modify'], type: 'react-icons' },
  { name: 'share', icon: TbShare, keys: ['share', 'send', 'social'], type: 'react-icons' },
  { name: 'download', icon: TbDownload, keys: ['download', 'save', 'arrow-down'], type: 'react-icons' },
  { name: 'upload', icon: TbUpload, keys: ['upload', 'send', 'arrow-up'], type: 'react-icons' },
  { name: 'lock', icon: TbLock, keys: ['lock', 'security', 'private'], type: 'react-icons' },
  { name: 'eye', icon: TbEye, keys: ['eye', 'view', 'visible'], type: 'react-icons' },
  { name: 'eye-off', icon: TbEyeOff, keys: ['eye-off', 'hide', 'invisible'], type: 'react-icons' },
  { name: 'plus', icon: TbPlus, keys: ['plus', 'add', 'new'], type: 'react-icons' },
  { name: 'minus', icon: TbMinus, keys: ['minus', 'remove', 'subtract'], type: 'react-icons' },
  { name: 'x', icon: TbX, keys: ['x', 'close', 'cancel'], type: 'react-icons' },
  { name: 'check', icon: TbCheck, keys: ['check', 'done', 'complete'], type: 'react-icons' },
  { name: 'circle', icon: TbCircle, keys: ['circle', 'round', 'shape'], type: 'react-icons' },
  { name: 'square', icon: TbSquare, keys: ['square', 'box', 'shape'], type: 'react-icons' },
  { name: 'triangle', icon: TbTriangle, keys: ['triangle', 'shape', 'warning'], type: 'react-icons' },
  { name: 'menu', icon: TbMenu, keys: ['menu', 'hamburger', 'list'], type: 'react-icons' },
  { name: 'refresh', icon: TbRefresh, keys: ['refresh', 'reload', 'update'], type: 'react-icons' },
  { name: 'filter', icon: TbFilter, keys: ['filter', 'funnel', 'sort'], type: 'react-icons' },
  { name: 'link', icon: TbLink, keys: ['link', 'chain', 'url'], type: 'react-icons' },
  { name: 'cloud', icon: TbCloud, keys: ['cloud', 'storage', 'weather'], type: 'react-icons' },
  { name: 'sun', icon: TbSun, keys: ['sun', 'day', 'light'], type: 'react-icons' },
  { name: 'moon', icon: TbMoon, keys: ['moon', 'night', 'dark'], type: 'react-icons' },
  { name: 'umbrella', icon: TbUmbrella, keys: ['umbrella', 'rain', 'protection'], type: 'react-icons' },
  { name: 'flag', icon: TbFlag, keys: ['flag', 'mark', 'report'], type: 'react-icons' },
  { name: 'tag', icon: TbTag, keys: ['tag', 'label', 'category'], type: 'react-icons' },
  { name: 'music', icon: TbMusic, keys: ['music', 'note', 'sound'], type: 'react-icons' },
  { name: 'video', icon: TbVideo, keys: ['video', 'movie', 'film'], type: 'react-icons' },
  { name: 'microphone', icon: TbMicrophone, keys: ['microphone', 'audio', 'record'], type: 'react-icons' },
  { name: 'volume', icon: TbVolume, keys: ['volume', 'sound', 'speaker'], type: 'react-icons' },
  { name: 'wifi', icon: TbWifi, keys: ['wifi', 'wireless', 'internet'], type: 'react-icons' },
  { name: 'battery', icon: TbBattery, keys: ['battery', 'power', 'energy'], type: 'react-icons' },
  { name: 'briefcase', icon: TbBriefcase, keys: ['briefcase', 'work', 'job'], type: 'react-icons' },
  { name: 'shopping-cart', icon: TbShoppingCart, keys: ['shopping-cart', 'buy', 'purchase'], type: 'react-icons' },
  { name: 'credit-card', icon: TbCreditCard, keys: ['credit-card', 'payment', 'money'], type: 'react-icons' },
  { name: 'printer', icon: TbPrinter, keys: ['printer', 'print', 'document'], type: 'react-icons' },
];

