import {
  IconBooks,
  IconBrain,
  IconBuildingBank,
  IconChartHistogram,
  IconClipboardText,
  IconCreditCard,
  IconDatabasePlus,
  IconEditCircle,
  IconFiles,
  IconFileText,
  IconForms,
  IconId,
  IconMasksTheater,
  IconMessageChatbot,
  IconReportMoney,
  IconSocial,
  IconUserCircle,
} from '@tabler/icons-react';

const banking = [
  {
    name: 'Borrower insights',
    slug: 'borrower-insights',
    date: '1/2/2024',
    description: `Optimize transactions with AI-driven insights.`,
    backgroundColor: '!bg-sky-700',
    textColor: '!text-sky-700',
    icon: IconFileText,
    link: '/banking',
    status: 'coming-soon',
    categories: ['banking'],
    type: 'document',
    summary: `Analyze customer's financial behavior for lending decisioning in a few seconds. All bank statement formats supported`,
    features: [
      `Pattern analysis`,
      `Decision discovery`,
      `Every statement format`,
      `Visualized result.`,
      `Tap AI Models`,
      `APIs for integration`,
    ],
    flow: [
      `Upload or connect statement directly from bank`,
      `Our extraction and analysis model takes over`,
      `Engage with result via chat, infographics or API`,
      `Bambi can also help with decisioning.`,
    ],
  },
  {
    name: 'Customer insights',
    slug: 'customer-insights',
    date: '1/2/2024',
    description: `Understand behaviors through insightful analysis.`,
    backgroundColor: '!bg-yellow-700',
    textColor: '!text-yellow-700',
    icon: IconUserCircle,
    link: '/banking',
    status: 'coming-soon',
    categories: ['banking'],
    type: 'document',
    summary: `Unlock customer insights and drive personalized strategies with our AI-powered customer understanding dashboard.`,
    features: [
      `Customer Segmentation`,
      `Behavior Analysis`,
      `Demographic Insights`,
      `Purchase Patterns`,
      `Visualized result`,
      `APIs for integration`,
    ],
    flow: [
      `Compiles data from various sources`,
      `Examines historical behavior, generating insights into purchasing patterns and interactions.`,
      `Engage with the result via chat, infographics or API`,
    ],
  },
  {
    name: 'Portfolio insights',
    slug: 'portfolio-insights',
    date: '1/2/2024',
    description: `Manage risk, enhance performance intelligently`,
    backgroundColor: '!bg-red-700',
    textColor: '!text-red-700',
    icon: IconCreditCard,
    link: '/banking',
    status: 'coming-soon',
    categories: ['banking'],
    type: 'document',
    summary: `Effectively manage your credit portfolio using our AI-powered dashboard, optimizing risk assessment and strategic decision-making`,
    features: [
      `Risk Assessment`,
      `Portfolio Overview`,
      `Credit Scoring`,
      `Payment Trends`,
      `Client Profiles`,
      `Default Prediction.`,
      `Performance Analysis`,
    ],
    flow: [
      `The dashboard compiles diverse data sources.`,
      `Evaluates risks`,
      `Tracks customer’s behavior over time.`,
      `Sends alerts about significant changes in customer behavior.`,
    ],
  },
  {
    name: 'Treasury insights',
    slug: 'treasury-insights',
    date: '1/2/2024',
    description: `Unlock actionable treasury insights`,
    backgroundColor: '!bg-teal-700',
    textColor: '!text-teal-700',
    icon: IconReportMoney,
    link: '/banking',
    status: 'coming-soon',
    categories: ['banking'],
    type: 'document',
    summary: `Unlock actionable treasury insights with our advanced dashboard.`,
    features: [
      `Financial Analytics`,
      `Risk Assessment`,
      `Cash Management`,
      `Market Trends`,
      `Investment Options`,
      `Liquidity Monitoring`,
      `Portfolio Analysis`,
      `Asset Allocation`,
      `Compliance Tracking`,
      `Treasury Optimization`,
    ],
    flow: [
      `Collects financial data from various sources comprehensively.`,
      `Evaluates market and credit risks to ensure stability.`,
      `Predicts future cash flows based on historical data analysis.`,
      `Suggests strategies to maximize returns and minimize risks.`,
      `Monitors changes and ensures adherence to financial regulations.`,
    ],
  },
  {
    name: 'Credit modelling',
    slug: 'credit-modelling',
    date: '1/2/2024',
    description: `Accurate credit assessment through advanced techniques.`,
    backgroundColor: '!bg-orange-700',
    textColor: '!text-orange-700',
    icon: IconChartHistogram,
    link: '/banking',
    status: 'coming-soon',
    categories: ['banking'],
    type: 'document',
    summary: `Optimize lending decisions with our AI credit score modeling dashboard, empowering accurate risk assessment and informed credit approvals.`,
    features: [
      `Credit Analysis`,
      `Risk Evaluation`,
      `Payment History`,
      `Debt Utilization`,
      `Financial Health`,
      `Predictive Power`,
      `Trend Tracking`,
    ],
    flow: [
      `Data gathering from various sources, to build a comprehensive credit profile.`,
      `Extracts key features and identifies patterns that contribute to creditworthiness.`,
      `Calculates credit scores based on analyzed data`,
      `Continuously updates the credit scoring model with new data.`,
    ],
  },
];

const document = [
  {
    name: 'Analyze any document',
    slug: 'documents',
    date: '1/2/2024',
    description: `Personalized insights for precise analysis.`,
    backgroundColor: '!bg-red-800',
    textColor: '!text-red-800',
    icon: IconEditCircle,
    link: '/documents',
    status: 'coming-soon',
    categories: ['document'],
    type: 'document',
    summary: 'Extracting valuable insights to inform data-driven decisions.',
    features: [
      `Custom Insights`,
      `Report Parsing`,
      `Visual Summaries`,
      `Predictive Trends`,
      `Data Mapping`,
      `Anomaly Detection`,
    ],
    flow: [
      `Upload your custom report.`,
      `Our extraction and analysis model takes over`,
      `Engage with result via chat, infographics or API`,
      `Bambi can also help with decisioning.`,
    ],
  },
  {
    name: 'Generate conversation',
    slug: 'conversation',
    date: '1/2/2024',
    description: `Support for efficient decision-making processes.`,
    backgroundColor: '!bg-blue-700',
    textColor: '!text-blue-700',
    icon: IconMessageChatbot,
    link: '/conversation',
    status: 'coming-soon',
    categories: ['document'],
    summary: `Unlock data-driven insights with an advanced embedded AI assistant,  information retrieval and decision-making.`,
    features: [
      `Data Insights`,
      `AI Analytics`,
      `Advanced Search`,
      `Real-time Trends`,
      `Predictive Analysis`,
      `Custom Reports`,
      `Interactive Visuals`,
    ],
    flow: [
      `Users interact naturally with the app, asking questions or providing data-related requests.`,
      `Advanced AI processes inquiries, applying complex analytics to retrieve relevant insights from the data.`,
      `Tanslates AI-generated insights into user-friendly visualizations and reports.`,
      `Users receive real-time, actionable insights, empowering informed decisions and streamlined data-driven actions.`,
    ],
  },
  {
    name: 'Generate infographics',
    slug: 'infographics',
    date: '1/2/2024',
    description: `Transform data into visuals with our infographic dashboard`,
    backgroundColor: '!bg-red-700',
    textColor: '!text-red-700',
    icon: IconChartHistogram,
    link: '/infographics',
    status: 'coming-soon',
    categories: ['document'],
    summary: `Transform data into visuals with our infographic dashboard`,
    features: [
      `Infographic Creation`,
      `Visual Design`,
      `Data Integration`,
      `Custom Templates`,
      `Graphic Elements`,
      `Data Visualization`,
      `Export Options`,
      `Real-time Updates`,
    ],
    flow: [
      `Users upload or input data.`,
      `AI parses data and identifies key information.`,
      `Users choose infographic templates or styles.`,
      `AI arranges data visually within the selected design.`,
      `Users tweak colors, fonts, and additional visual elements.`,
    ],
  },
  {
    name: 'Generate forms',
    slug: 'forms',
    date: '1/2/2024',
    description: `Simplify data collection through automated processes.`,
    backgroundColor: '!bg-teal-700',
    textColor: '!text-teal-700',
    icon: IconForms,
    link: '/forms',
    status: 'coming-soon',
    categories: ['document'],
    summary: `Improve form processes with our AI dashboard, enabling end-to-end digital form management from creation to analysis.`,
    features: [
      `Form Generation`,
      `Automated Filling`,
      `Approval Workflow`,
      `Custom Templates`,
      `Digital Signatures`,
      `Collaborative Editing`,
      `Smart Forms`,
    ],
    flow: [
      `Users create digital forms or choose from templates using the AI dashboard's interface.`,
      `Data is automatically populated into forms using integrated systems or user inputs.`,
      `Forms are routed through approval processes, with notifications and collaborative options within the dashboard.`,
      `Aggregates and analyzes form data, extracting insights and trends.`,
      `AI-powered analytics provide actionable insights, aiding decision-making and process optimization based on form data.`,
    ],
  },
];

const identity = [
  {
    name: 'Government IDs',
    slug: 'govt-id',
    date: '1/2/2024',
    description: `Identity verification for reduced fraudulent activities.`,
    backgroundColor: '!bg-teal-700',
    textColor: '!text-teal-700',
    icon: IconId,
    link: '/govt-id',
    status: 'coming-soon',
    categories: ['identity'],
    type: 'document',
    summary: `Enhance identity verification and compliance with our AI dashboard, providing insights through Government ID analysis.`,
    features: [
      `ID Verification`,
      `Document Analysis`,
      `Security Checks`,
      `Fraud Detection`,
      `Biometric Match`,
      `Data Extraction`,
      `Compliance Tracking`,
      `User Profiling`,
      `Authentication Insights`,
      `Regulatory Compliance`,
    ],
    flow: [
      `Securely acquires government data from authorized sources or users.`,
      `Process and extract relevant information from the government data.`,
      `Conducts in-depth analysis, including identity verification, data validation, and compliance checks.`,
      `Users receive actionable insights, ensuring data integrity and informed decision-making in compliance with government regulations.`,
    ],
  },
  {
    name: 'Social analytics',
    slug: 'social-analytics',
    date: '1/2/2024',
    description: `Extract insights from analyzed social data.`,
    backgroundColor: '!bg-blue-700',
    textColor: '!text-blue-700',
    icon: IconSocial,
    link: '/social-analytics',
    status: 'coming-soon',
    categories: ['identity'],
    summary: `Gain deep social media insights and optimize engagement strategies.`,
    features: [
      `Trend Insights`,
      `Engagement Analysis`,
      `Sentiment Tracking`,
      `Influencer insights`,
      `Demographic Breakdown`,
      `Content Performance`,
      `Audience Segmentation`,
      `Virality Prediction`,
    ],
    flow: [
      `Collects data from various social media platforms,`,
      `Analyzing patterns in social data.`,
      `Identifies emerging trends, hashtags, and topics, allowing users to stay ahead of relevant discussions.`,
      `Measures user engagement metrics.`,
      `Helps identify influential figures and potential brand collaborators within the social sphere.`,
    ],
  },
  {
    name: 'Psychometric',
    slug: 'psychometric',
    date: '1/2/2024',
    description: `Decipher traits to enable precise assessment.`,
    backgroundColor: '!bg-yellow-700',
    textColor: '!text-yellow-700',
    icon: IconBrain,
    link: '/psychometric',
    status: 'coming-soon',
    categories: ['identity'],
    summary: `Utilize psychometrics to create detailed customer profiles, enabling personalized interactions and tailored experiences.`,
    features: [
      `Personality Insights`,
      `Customer Profiling`,
      `Behavioral Traits`,
      `Psychometric Analysis`,
      `User Characteristics`,
      `Trait Mapping`,
      `Personal Preferences`,
      `Psychological Traits`,
      `Behavior Patterns`,
      `Customer Segmentation`,
    ],
    flow: [
      `Design a set of psychometric questions.`,
      `Customers answer the psychometric questions providing data on their psychological characteristics and preferences.`,
      `System analyzes the collected responses, using advanced algorithms to extract patterns, correlations, and traits to build a comprehensive customer profile.`,
      `The dashboard maps customers' responses to specific psychological traits and categorizes`,
      `Generates actionable insights based on the gathered data.`,
    ],
  },
  {
    name: 'Alternative data',
    slug: 'alternative-data',
    date: '1/2/2024',
    description: `Unconventional sources offer comprehensive insights.`,
    backgroundColor: '!bg-orange-700',
    textColor: '!text-orange-700',
    icon: IconDatabasePlus,
    link: '/alternative-data',
    status: 'coming-soon',
    categories: ['identity'],
    summary: `Uncover valuable insights from alternative data sources, enhancing informed decision-making.`,
    features: [
      `Diverse Sources`,
      `Unconventional Insights`,
      `Alternative Analytics`,
      `Non-traditional Data`,
      `Varied Perspectives`,
      `Non-standard Metrics`,
      `Unorthodox Patterns`,
      `Unique Signals`,
      `Unconventional Trends`,
    ],
    flow: [
      `Collects diverse alternative data from a wide range of sources, including social media, news, web scraping, and IoT devices.`,
      `Data Cleaning: The collected data undergoes Thorough cleaning and preprocessing of collected data.`,
      `Identify relevant patterns, signals, and metrics within the alternative data, converting raw information into actionable insights.`,
      `The system contextualizes the extracted insights, correlating them with existing traditional data and market trends for a comprehensive`,
      `Intuitive visualizations of results.`,
    ],
  },
];

const accounting = [
  {
    name: 'Cash-flow insights',
    slug: 'cash-flow',
    date: '1/2/2024',
    description: `Unlock cash-flow insights for informed financial decisions.`,
    backgroundColor: '!bg-sky-700',
    textColor: '!text-sky-700',
    icon: IconFileText,
    link: '/cash-flow',
    status: 'coming-soon',
    categories: ['accounting'],
    summary: `Unlock cash-flow insights for informed financial decisions.`,
    features: [
      `Cash Projection`,
      `Expense Tracking`,
      `Income Analysis`,
      `Financial Forecast`,
      `Real-time Updates`,
      `Budget Monitoring`,
      `Payment Trends`,
      `Liquidity Assessment`,
      `Income Streams`,
      `Financial Health`,
    ],
    flow: [
      `Collects financial data from various sources comprehensively.`,
      `Examines past financial records for patterns and trends.`,
      `Utilizes advanced models to forecast future cash flows.`,
      `Tracks and alerts on cash flow changes instantly.`,
      `Generates tailored reports with actionable cash-flow insights.`,
    ],
  },
  {
    name: 'Financial report',
    slug: 'financial-report',
    date: '1/2/2024',
    description: `Accurate reports for insights and decision-making.`,
    backgroundColor: '!bg-indigo-700',
    textColor: '!text-indigo-700',
    icon: IconBooks,
    link: '/financial-report',
    status: 'coming-soon',
    categories: ['accounting'],
    type: 'document',
    summary: `Streamline decision-making and track key metrics through intuitive visualizations for smarter financial strategies`,
    features: [
      `Performance Overview`,
      `Trend Analysis`,
      `Risk Assessment`,
      `Forecast Accuracy`,
      `Profit Insights`,
      `Cost Tracking`,
      `Portfolio Health`,
    ],
    flow: [
      `Upload your financial report.`,
      `Our extraction and analysis model takes over`,
      `Engage with result via chat, infographics or API`,
      `Bambi can also help with decisioning.`,
    ],
  },
  {
    name: 'Invoices & Receipts',
    slug: 'invoice',
    date: '1/2/2024',
    description: `Streamlined automation for financial tracking.`,
    backgroundColor: '!bg-amber-700',
    textColor: '!text-amber-700',
    icon: IconClipboardText,
    link: '/invoice',
    status: 'coming-soon',
    categories: ['accounting'],
    type: 'document',
    summary:
      'Comprehensive insights through advanced invoice analysis. Financial tracking and analysis, providing accurate insights from receipts and invoices.',
    features: [
      `Receipt Extraction`,
      `Expense Tracking`,
      `Item Categorization`,
      `Accuracy Check`,
      `Payment Verification`,
      `Automated Auditing`,
      `Fraud Detection.`,
    ],
    flow: [
      `Upload documents`,
      `Our analysis model extracts key information like date, amount, and vendor details`,
      `Validation of extracted data`,
      `The dashboard intelligently categorizes items on receipts and invoices.`,
      `Engage with result via infographics or API`,
    ],
  },
  {
    name: 'Fraud',
    slug: 'fraud',
    date: '1/2/2024',
    description: `Thwart fraud, ensuring secure transactions.`,
    backgroundColor: '!bg-red-700',
    textColor: '!text-red-700',
    icon: IconMasksTheater,
    link: '/fraud',
    status: 'coming-soon',
    categories: ['accounting'],
    summary: `Protect your business from fraud, swiftly identify suspicious patterns and transactions, enhancing security and minimizing risks`,
    features: [
      `Real-time alerts`,
      `Anomaly detection`,
      `Pattern recognition`,
      `Risk assessment`,
      `Transaction monitoring`,
      `Behavioral analysis`,
      `Predictive modeling`,
    ],
    flow: [
      `Collects data from multiple sources, to create a comprehensive view for fraud analysis.`,
      `Identifies deviations from normal patterns in real-time, flagging potentially fraudulent activities.`,
      `Examines user actions over time for potential signs of fraud.`,
      `Spots recurring patterns indicative of fraud schemes`,
      `Triggers alerts and recommendations when suspicious activities are identified.`,
    ],
  },
];

const products = [...document, ...banking, ...identity, ...accounting];

export const categories = [
  {
    id: 'banking',
    name: 'Banking',
    slug: 'banking',
    summary:
      'Our data-driven solutions for the banking sector encompass a wide range of services. We provide in-depth analyses of customer behavior, risk assessment, and market trends. This empowers banks to offer tailored financial products and services, optimize operational efficiency, and ensure compliance with regulatory standards. Additionally, we assist in developing strategies for customer retention and acquisition, enabling banks to stay competitive in a rapidly evolving financial landscape.',
    icon: IconBuildingBank,
    colors: {
      bg: '!bg-sky-700',
      color: '!text-sky-700',
    },
    path: '/banking',
    status: 'pending',
  },
  {
    id: 'document',
    name: 'Documents',
    slug: 'documents',
    summary: `Our document processing solutions utilize advanced algorithms and natural language processing to extract valuable insights from various types of documents. Whether it's contracts, reports, or invoices, our technology can rapidly analyze and extract key information, enabling businesses to make informed decisions. This capability enhances operational efficiency, reduces manual data entry, and ensures compliance with document-related requirements. Additionally, our data-driven approach empowers businesses to derive actionable intelligence from their documents, driving strategic decision-making and operational excellence.`,
    icon: IconFiles,
    colors: {
      bg: '!bg-teal-700',
      color: '!text-teal-700',
    },
    path: '/documents',
    status: 'active',
  },
  { id: 'accounting', name: 'Accounting' },
  { id: 'identity', name: 'Identity' },
];

export default products;
