import {
  TbHeart,
  TbHeartFilled,
  TbUser,
  TbUserFilled,
  TbHome,
  TbHomeFilled,
  TbSearch,
  TbSettings,
  TbSettingsFilled,
  TbBell,
  TbBellFilled,
  TbMail,
  TbMailFilled,
  TbPhone,
  TbPhoneFilled,
  TbCamera,
  TbCameraFilled,
  TbCalendar,
  TbCalendarFilled,
  TbClock,
  TbClockFilled,
  TbMap,
  TbStar,
  TbStarFilled,
  TbBookmark,
  TbBookmarkFilled,
  TbTrash,
  TbTrashFilled,
  TbEdit,
  TbShare,
  TbDownload,
  TbUpload,
  TbLock,
  TbLockFilled,
  TbEye,
  TbEyeFilled,
  TbEyeOff,
  TbPlus,
  TbMinus,
  TbX,
  TbCheck,
  TbCircle,
  TbSquare,
  TbTriangle,
  TbMenu,
  TbRefresh,
  TbFilter,
  TbLink,
  TbCloud,
  TbSun,
  TbMoon,
  TbUmbrella,
  TbFlag,
  TbTag,
  TbMusic,
  TbVideo,
  TbMicrophone,
  TbVolume,
  TbWifi,
  TbBattery,
  TbBriefcase,
  TbShoppingCart,
  TbCreditCard,
  TbPrinter,
  TbCircleFilled,
  TbWoman,
  TbWomanFilled,
  TbMan,
  TbManFilled,
  TbSquareFilled,
  TbTriangleFilled,
} from 'react-icons/tb';

export default [
  { name: 'male', icon: TbMan, filledIcon: TbManFilled, keywords: ['male', 'man', 'user'], type: 'react-icons' },
  {
    name: 'female',
    icon: TbWoman,
    filledIcon: TbWomanFilled,
    keywords: ['female', 'woman', 'user'],
    type: 'react-icons',
  },
  { name: 'heart', icon: TbHeart, filledIcon: TbHeartFilled, keywords: ['heart', 'love', 'like'], type: 'react-icons' },
  {
    name: 'user',
    icon: TbUser,
    filledIcon: TbUserFilled,
    keywords: ['user', 'person', 'profile'],
    type: 'react-icons',
  },
  {
    name: 'home',
    icon: TbHome,
    filledIcon: TbHomeFilled,
    keywords: ['home', 'house', 'residence'],
    type: 'react-icons',
  },
  {
    name: 'search',
    icon: TbSearch,
    filledIcon: TbSearch,
    keywords: ['search', 'find', 'magnify'],
    type: 'react-icons',
  },
  {
    name: 'settings',
    icon: TbSettings,
    filledIcon: TbSettingsFilled,
    keywords: ['settings', 'gear', 'preferences'],
    type: 'react-icons',
  },
  {
    name: 'bell',
    icon: TbBell,
    filledIcon: TbBellFilled,
    keywords: ['bell', 'notification', 'alert'],
    type: 'react-icons',
  },
  { name: 'mail', icon: TbMail, filledIcon: TbMailFilled, keywords: ['mail', 'email', 'message'], type: 'react-icons' },
  {
    name: 'phone',
    icon: TbPhone,
    filledIcon: TbPhoneFilled,
    keywords: ['phone', 'call', 'telephone'],
    type: 'react-icons',
  },
  {
    name: 'camera',
    icon: TbCamera,
    filledIcon: TbCameraFilled,
    keywords: ['camera', 'photo', 'picture'],
    type: 'react-icons',
  },
  {
    name: 'calendar',
    icon: TbCalendar,
    filledIcon: TbCalendarFilled,
    keywords: ['calendar', 'date', 'schedule'],
    type: 'react-icons',
  },
  {
    name: 'clock',
    icon: TbClock,
    filledIcon: TbClockFilled,
    keywords: ['clock', 'time', 'watch'],
    type: 'react-icons',
  },
  { name: 'map', icon: TbMap, filledIcon: TbMap, keywords: ['map', 'location', 'navigation'], type: 'react-icons' },
  {
    name: 'star',
    icon: TbStar,
    filledIcon: TbStarFilled,
    keywords: ['star', 'favorite', 'rating'],
    type: 'react-icons',
  },
  {
    name: 'bookmark',
    icon: TbBookmark,
    filledIcon: TbBookmarkFilled,
    keywords: ['bookmark', 'save', 'favorite'],
    type: 'react-icons',
  },
  {
    name: 'trash',
    icon: TbTrash,
    filledIcon: TbTrashFilled,
    keywords: ['trash', 'delete', 'remove'],
    type: 'react-icons',
  },
  { name: 'edit', icon: TbEdit, filledIcon: TbEdit, keywords: ['edit', 'pencil', 'modify'], type: 'react-icons' },
  { name: 'share', icon: TbShare, filledIcon: TbShare, keywords: ['share', 'send', 'social'], type: 'react-icons' },
  {
    name: 'download',
    icon: TbDownload,
    filledIcon: TbDownload,
    keywords: ['download', 'save', 'arrow-down'],
    type: 'react-icons',
  },
  {
    name: 'upload',
    icon: TbUpload,
    filledIcon: TbUpload,
    keywords: ['upload', 'send', 'arrow-up'],
    type: 'react-icons',
  },
  {
    name: 'lock',
    icon: TbLock,
    filledIcon: TbLockFilled,
    keywords: ['lock', 'security', 'private'],
    type: 'react-icons',
  },
  { name: 'eye', icon: TbEye, filledIcon: TbEyeFilled, keywords: ['eye', 'view', 'visible'], type: 'react-icons' },
  {
    name: 'eye-off',
    icon: TbEyeOff,
    filledIcon: TbEyeOff,
    keywords: ['eye-off', 'hide', 'invisible'],
    type: 'react-icons',
  },
  { name: 'plus', icon: TbPlus, keywords: ['plus', 'add', 'new'], type: 'react-icons' },
  { name: 'minus', icon: TbMinus, keywords: ['minus', 'remove', 'subtract'], type: 'react-icons' },
  { name: 'x', icon: TbX, keywords: ['x', 'close', 'cancel'], type: 'react-icons' },
  { name: 'check', icon: TbCheck, keywords: ['check', 'done', 'complete'], type: 'react-icons' },
  {
    name: 'circle',
    icon: TbCircle,
    filledIcon: TbCircleFilled,
    keywords: ['circle', 'round', 'shape'],
    type: 'react-icons',
  },
  {
    name: 'square',
    icon: TbSquare,
    filledIcon: TbSquareFilled,
    keywords: ['square', 'box', 'shape'],
    type: 'react-icons',
  },
  {
    name: 'triangle',
    icon: TbTriangle,
    filledIcon: TbTriangleFilled,
    keywords: ['triangle', 'shape', 'warning'],
    type: 'react-icons',
  },
  { name: 'menu', icon: TbMenu, keywords: ['menu', 'hamburger', 'list'], type: 'react-icons' },
  { name: 'refresh', icon: TbRefresh, keywords: ['refresh', 'reload', 'update'], type: 'react-icons' },
  { name: 'filter', icon: TbFilter, keywords: ['filter', 'funnel', 'sort'], type: 'react-icons' },
  { name: 'link', icon: TbLink, keywords: ['link', 'chain', 'url'], type: 'react-icons' },
  { name: 'cloud', icon: TbCloud, keywords: ['cloud', 'storage', 'weather'], type: 'react-icons' },
  { name: 'sun', icon: TbSun, keywords: ['sun', 'day', 'light'], type: 'react-icons' },
  { name: 'moon', icon: TbMoon, keywords: ['moon', 'night', 'dark'], type: 'react-icons' },
  { name: 'umbrella', icon: TbUmbrella, keywords: ['umbrella', 'rain', 'protection'], type: 'react-icons' },
  { name: 'flag', icon: TbFlag, keywords: ['flag', 'mark', 'report'], type: 'react-icons' },
  { name: 'tag', icon: TbTag, keywords: ['tag', 'label', 'category'], type: 'react-icons' },
  { name: 'music', icon: TbMusic, keywords: ['music', 'note', 'sound'], type: 'react-icons' },
  { name: 'video', icon: TbVideo, keywords: ['video', 'movie', 'film'], type: 'react-icons' },
  { name: 'microphone', icon: TbMicrophone, keywords: ['microphone', 'audio', 'record'], type: 'react-icons' },
  { name: 'volume', icon: TbVolume, keywords: ['volume', 'sound', 'speaker'], type: 'react-icons' },
  { name: 'wifi', icon: TbWifi, keywords: ['wifi', 'wireless', 'internet'], type: 'react-icons' },
  { name: 'battery', icon: TbBattery, keywords: ['battery', 'power', 'energy'], type: 'react-icons' },
  { name: 'briefcase', icon: TbBriefcase, keywords: ['briefcase', 'work', 'job'], type: 'react-icons' },
  { name: 'shopping-cart', icon: TbShoppingCart, keywords: ['shopping-cart', 'buy', 'purchase'], type: 'react-icons' },
  { name: 'credit-card', icon: TbCreditCard, keywords: ['credit-card', 'payment', 'money'], type: 'react-icons' },
  { name: 'printer', icon: TbPrinter, keywords: ['printer', 'print', 'document'], type: 'react-icons' },
];
