const fields = {
  nigeria: [
    'abia',
    'abuja',
    'adamawa',
    'akwa ibom',
    'anambra',
    'bauchi',
    'bayelsa',
    'benue',
    'borno',
    'cross river',
    'delta',
    'ebonyi',
    'edo',
    'ekiti',
    'enugu',
    'gombe',
    'imo',
    'jigawa',
    'kaduna',
    'kano',
    'katsina',
    'kebbi',
    'kogi',
    'kwara',
    'lagos',
    'nasarawa',
    'niger',
    'ogun',
    'ondo',
    'osun',
    'oyo',
    'plateau',
    'rivers',
    'sokoto',
    'taraba',
    'yobe',
    'zamfara',
  ],
  europe: [
    'Russia',
    'Norway',
    'Spain',
    'Sweden',
    'Ukraine',
    'France',
    'Italy',
    'Turkey',
    'Finland',
    'United Kingdom',
    'Germany',
    'Svalbard and Jan Mayen',
    'Poland',
    'Belarus',
    'Greece',
    'Romania',
    'Iceland',
    'Croatia',
    'Austria',
    'Azerbaijan',
    'Hungary',
    'Bulgaria',
    'Latvia',
    'Ireland',
    'Portugal',
    'Georgia',
    'Serbia',
    'Czechia',
    'Lithuania',
    'Estonia',
    'Denmark',
    'Slovakia',
    'Netherlands',
    'Bosnia and Herzegovina',
    'Moldova',
    'Switzerland',
    'Belgium',
    'Armenia',
    'Albania',
    'Slovenia',
    'North Macedonia',
    'Montenegro',
    'Cyprus',
    'Kosovo',
    'Luxembourg',
    // 'Malta',
    // 'Vatican city'
  ],
  africa: [
    'Algeria',
    'Democratic Republic of Congo',
    'Mali',
    'Sudan',
    'Libya',
    'South Africa',
    'Niger',
    'Mozambique',
    'Ethiopia',
    'Chad',
    'Angola',
    'Namibia',
    'Mauritania',
    'Somalia',
    'Tanzania',
    'Egypt',
    'Nigeria',
    'Zambia',
    'Central African Republic',
    'Morocco',
    'South Sudan',
    'Madagascar',
    'Cameroon',
    'Botswana',
    'Kenya',
    'Republic of Congo',
    'Western Sahara',
    'Zimbabwe',
    'Burkina Faso',
    'Côte d Ivoire',
    'Guinea',
    'Eritrea',
    'Gabon',
    'Uganda',
    'Tunisia',
    'Ghana',
    'Senegal',
    'Malawi',
    'Benin',
    'Liberia',
    'Sierra Leone',
    'Togo',
    'Guinea-Bissau',
    'Lesotho',
    'Burundi',
    'Rwanda',
    'Djibouti',
    'Equatorial Guinea',
    'Eswatini',
    'Gambia',
    'Reunion',
    'Canary Islands',
    'Mauritius',
],
  'north-america': [
    'United States',
    'Canada',
    'Greenland',
    'Mexico',
    'Cuba',
    'Nicaragua',
    'Honduras',
    'Guatemala',
    'Panama',
    'Costa Rica',
    'Dominican Republic',
    'Haiti',
    'Belize',
    'El Salvador',
    'Jamaica',
    'Puerto Rica',
  ],
  world: [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo (Congo-Brazzaville)',
    'Congo (Congo-Kinshasa)',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'East Timor (Timor-Leste)',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea, North (North Korea)',
    'Korea, South (South Korea)',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar (Burma)',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
  ],
  asia: [
    'Afghanistan',
    'Armenia',
    'Azerbaijan',
    'Bahrain',
    'Bangladesh',
    'Bhutan',
    'Brunei',
    'Cambodia',
    'China',
    'Cyprus',
    'Georgia',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Israel',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Lebanon',
    'Malaysia',
    'Maldives',
    'Mongolia',
    'Myanmar (Burma)',
    'Nepal',
    'North Korea',
    'Oman',
    'Pakistan',
    'Palestine',
    'Philippines',
    'Qatar',
    'Russia',
    'Saudi Arabia',
    'Singapore',
    'South Korea',
    'Sri Lanka',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Thailand',
    'Timor Leste',
    'Turkey',
    'Turkmenistan',
    'United Arab Emirates',
    'Uzbekistan',
    'Vietnam',
  ],
  'south-america': [
    'Brazil',
    'Argentina',
    'Chile',
    'Peru',
    'Colombia',
    'Bolivia',
    'Venezuela',
    'Paraguay',
    'Ecuador',
    'Guyana',
    'Uruguay',
    'Suriname',
    'French Guiana',
    'Falkland Islands',
  ],
  algeria: [
    'Tamanghasset',
    'Adrar',
    'Illizi',
    'Ouargla',
    'Béchar',
    'Tindouf',
    'Ghardaïa',
    'El Bayadh',
    'El Oued',
    'Djelfa',
    'Laghouat',
    'Biskra',
    'Naama',
    "M'Sila",
    'Tiaret',
    'Batna',
    'Tébessa',
    'Sidi Bel Abbès',
    'Tlemcen',
    'Khenchela',
    'Médéa',
    'Oum el Bouaghi',
    'Sétif',
    'Mascara',
    'Saïda',
    'Relizane',
    'Bouira',
    'Skikda',
    'Béjaïa',
    'Bordj Bou Arréridj',
    'Souk Ahras',
    'Chlef',
    'Aïn Defla',
    'Guelma',
    'Mila',
    'Aïn Témouchent',
    'Mostaganem',
    'Oran',
    'El Tarf',
    'Tissemsilt',
    'Jijel',
    'Tizi Ouzou',
    'Constantine',
    'Tipaza',
    'Boumerdès',
    'Blida',
    'Annaba',
    'Alger',
  ],
  angola: [
    'Moxico',
    'Cuando Cubango',
    'Lunda Norte',
    'Malanje',
    'Bié',
    'Lunda Sul',
    'Huíla',
    'Cunene',
    'Uíge',
    'Cuanza Sul',
    'Namibe',
    'Benguela',
    'Zaire',
    'Bengo',
    'Huambo',
    'Cuanza Norte',
    'Cabinda',
    'Luanda',
  ],
  albania: [
    'Vlorë',
    'Shkodër',
    'Korçë',
    'Elbasan',
    'Gjirokastër',
    'Kukës',
    'Dibër',
    'Tiranë',
    'Lezhë',
    'Fier',
    'Berat',
    'Durrës',
  ],
  oceanic: [
    'Australia',
    'Indonesia',
    'New Zealand',
    'Papua New Guinea',
    'New Caledonia',
    'Fiji',
    'Solomon Islands',
    'Timor-Leste',
    'Vanuatu',
  ],
  'nigeria-regions': ['South West', 'South South', 'South East', 'North West', 'North East', 'North Central'],
  afghanistan: [
    'Badakhshan',
    'Hirat',
    'Hilmand',
    'Kandahar',
    'Farah',
    'Ghor',
    'Nimroz',
    'Ghazni',
    'Faryab',
    'Badghis',
    'Balkh',
    'Baghlan',
    'Paktika',
    'Bamyan',
    'Sari Pul',
    'Zabul',
    'Uruzgan',
    'Jawzjan',
    'Samangan',
    'Wardak',
    'Uruzgan',
    'Nuristan',
    'Nangarhar',
    'Kunduz',
    'Parwan',
    'Paktya',
    'Kunar',
    'Logar',
    'Khost',
    'Kabul',
    'Laghman',
    'Kapisa',
  ],
  austria: [
    'Lower Austria',
    'Styria',
    'Tyrol',
    'Upper Austria',
    'Salzburg',
    'Carinthia',
    'Burgenland',
    'Vorarlberg',
    'Vienna',
  ],
  argentina: [
    'Buenos Aires',
    'Santa Cruz',
    'Río Negro',
    'Chubut',
    'Salta',
    'Santa Fe',
    'Mendoza',
    'Cordoba',
    'La Pampa',
    'Formosa',
    'Catamarca',
    'Chaco',
    'La Rioja',
    'Neuquén',
    'Santiago del Estero',
    'San Juan',
    'Corrientes',
    'Entre Ríos',
    'Tierra del Fuego',
    'San Luis',
    'Jujuy',
    'Misiones',
    'Tucumán',
    'Ciudad de Buenos Aires', // this is not showing on the map
  ],
  azerbaijan: [
    'Baki',
    'Abseron',
    'Kalbajar',
    'Şəki',
    'Neftçala',
    'Quba',
    'Haciqabul',
    'Tovuz',
    'Lənkəran',
    'Goranboy',
    'Qusar',
    'Laçın',
    'Ismayilli',
    'Sabirabad',
    'Aghjabadi',
    'Qax',
    'Imisli',
    'Xizi',
    'Salyan',
    'Samux',
    'Xocavənd',
    'Zaqatala',
    'Bilasuvar',
    'Shamkir',
    'Kurdamir',
    'Xaçmaz',
    'Agstafa',
    'Qabala',
    'Yevlax',
    'Agsu',
    'Qobustan',
    'Samaxi',
    'Babek',
    'Gədəbəy',
    'Cəlilabad',
    'Beylagan',
    'Sabran',
    'Tartar',
    'Agdam',
    'Göygöl',
    'Füzuli',
    'Agdas',
    'Lerik',
    'Oguz',
    'Culfa',
    'Ordubad',
    'Cəbrayıl',
    'Barda',
    'Sharur',
    'Balakan',
    'Khojali',
    'Saatli',
    'Siazan',
    'Yardimli',
    'Zardab',
    'Qubadli',
    'Dashkasan',
    'Zangilan',
    'Sahbuz',
    'Masalli',
    'Qazax',
    'Ucar',
    'Göyçay',
    'Astara',
    'Kangarli',
    'Susa',
    'Sadarak',
    'Sumqayit',
    'Ganja',
    'Mingachevir',
    'Shirvan City',
    'Naxçıvan',
    'Şəki City',
    "Gegark'unik'",
    'Yevlax City',
    'Naftalan City',
    'Lənkəran City',
  ],
  benin: [
    'Borgou',
    'Alibori',
    'Atakora',
    'Collines',
    'Donga',
    'Zou',
    'Plateau',
    'Kouffo',
    'Atlantique',
    'Mono',
    'Ouémé',
    'Littoral',
  ],
  bangladesh: ['Chittagong', 'Dhaka', 'Khulna', 'Rangpur', 'Rajshahi', 'Sylhet', 'Mymensingh'],
  belarus: ['Vitsyebsk', 'Homyel', 'Minsk', 'Brest', 'Mahilyow', 'Hrodna', 'Minsk City'],
  bermuda: [
    'St.George',
    'Sandys',
    'Hamilton',
    'Southampton',
    'Warwick',
    'Paget',
    'Smiths',
    'Devonshire',
    'Hamilton',
    'St.George-Town',
  ],
  botswana: ['Central', 'Kgalagadi', 'Ghanzi', 'North West', 'Kweneng', 'Southern', 'Kgatleng', 'North East', 'Chobe'],
  bahrain: ['Al Janūbīyah', 'Ash Shamālīyah', 'Al ‘Āşimah', 'Al Muḩarraq'],
  bulgaria: [
    'Sofia-Grad',
    'Burgas',
    'Haskovo',
    'Plovdiv',
    'Blagoevgrad',
    'Dobrich',
    'Veliko Tarnovo',
    'Stara Zagora',
    'Vratsa',
    'Kyustendil',
    'Ruse',
    'Pazardzhik',
    'Lovech',
    'Varna',
    'Shumen',
    'Pleven',
    'Sliven',
    'Smolyan',
    'Yambol',
    'Montana',
    'Kardzhali',
    'Silistra',
    'Razgrad',
    'Vidin',
    'Targovishte',
    'Pernik',
    'Gabrovo',
    'Sofia',
  ],
  burkinafaso: [
    'Est',
    'Sahel',
    'Boucle du Mouhoun',
    'Hauts-Bassins',
    'Centre-Ouest',
    'Sud-Ouest',
    'Cascades',
    'Centre-Nord',
    'Centre-Est',
    'Nord',
    'Plateau-Central',
    'Centre-Sud',
    'Centre',
  ],
  burundi: [
    'Muyinga',
    'Ruyigi',
    'Makamba',
    'Gitega',
    'Rutana',
    'Cankuzo',
    'Bururi',
    'Cibitoke',
    'Ngozi',
    'Kirundo',
    'Karuzi',
    'Kayanza',
    'Rumonge',
    'Bujumbura Rural',
    'Bubanza',
    'Mwaro',
    'Muramvya',
    'Bujumbura Mairie',
  ],
  armenia: [
    "Gegark'unik",
    "Syunik'",
    'Loṙi',
    'Aragac̣otn',
    'Tavuš',
    'Širak',
    "Kotayk'",
    'Ararat',
    'Vayoć Jor',
    'Armavir',
    'Erevan',
  ],
  australia: [
    'Western Australia',
    'Queensland',
    'South Australia',
    'Northern Territory',
    'New South Wales',
    'Victoria',
    'Tasmania',
  ],
  belgium: [
    'Hainaut',
    'Luxembourg',
    'Liège',
    'Namur',
    'West Flanders',
    'East Flanders',
    'Limburg',
    'Antwerpen',
    'Flemish Brabant',
    'Walloon Brabant',
    'Brussels Capital Region',
  ],
  belize: ['Belize', 'Orange Walk', 'Cayo', 'Toledo', 'Corozal', 'Stann Creek'],
  bhutan: [
    'Wangdue Phodrang',
    'Gasa',
    'Lhuentse',
    'Sarpang',
    'Thimphu',
    'Bumthang',
    'Zhemgang',
    'Monggar',
    'Trashigang',
    'Samdrup Jongkhar',
    'Chhukha',
    'Trongsa',
    'Samtse',
    'Haa',
    'Trashi Yangtse',
    'Dagana',
    'Paro',
    'Pemagatshel',
    'Punakha',
  ],
  bolivia: ['Santa Cruz', 'El Beni', 'Potosí', 'La Paz', 'Pando', 'Chuquisaca', 'Cochabamba', 'Oruro', 'Tarija'],
  'bosnia-and-aerzegovina': ['Republika Srpska', 'Federacija Bosne i Hercegovine', 'Brčko distrikt'],
  brazil: [
    'Amazonas',
    'Pará',
    'Mato Grosso',
    'Minas Gerais',
    'Bahia',
    'Maranhão',
    'Rio Grande do Sul',
    'Goiás',
    'Mato Grosso do Sul',
    'São Paulo',
    'Piauí',
    'Tocantins',
    'Rondônia',
    'Roraima',
    'Acre',
    'Paraná',
    'Amapá',
    'Ceará',
    'Santa Catarina',
    'Pernambuco',
    'Rio de Janeiro',
    'Paraíba',
    'Rio Grande do Norte',
    'Espírito Santo',
    'Alagoas',
    'Sergipe',
  ],
  'brunei-darussalam': ['Belait', 'Tutong', 'Temburong', 'Brunei-Mua'],
  bahamas: [
    'North Andros',
    'Inagua',
    'Acklins',
    'Long Island',
    'Crooked Island and Long Cay',
    'South Andros',
    'Black Point',
    'Cat Island',
    'South Abaco',
    'Central Andros',
    'West Grand Bahama',
    'Central Abaco',
    'North Abaco',
    'Exuma',
    'East Grand Bahama',
    'North Eleuthera',
    'Mangrove Cay',
    'Mayaguana',
    'Central Eleuthera',
    'South Eleuthera',
    'Rum Cay',
    'New Providence',
    'San Salvador',
    "Moore's Island",
    'Berry Islands',
    'Spanish Wells',
    'Hope Town',
    'Ragged Island',
    'City of Freeport',
    'Harbour Island',
    'Grand Cay',
  ],
  chad: [
    'Borkou',
    'Tibesti',
    'Ennedi-Oest',
    'Batha',
    'Kanem',
    'Salamat',
    'Guéra',
    'Bahr el Gazel',
    'Moyen-Chari',
    'Chari-Baguirmi',
    'Sila',
    'Wadi Fira',
    'Hadjer-Lamis',
    'Ouaddaï',
    'Logone Oriental',
    'Lac',
    'Ennedi-Est',
    'Mayo-Kébbi-Est',
    'Tandjilé',
    'Mayo-Kébbi-Ouest',
    'Mandoul',
    'Ville de Ndjamena',
  ],
  colombia: [
    'Amazonas',
    'Caquetá',
    'Vichada',
    'Meta',
    'Guainia',
    'Antioquia',
    'Vaupés',
    'Chocó',
    'Guaviare',
    'Bolívar',
    'Casanare',
    'Boyacá',
    'Putumayo',
    'Nariño',
    'La Guajira',
    'Cauca',
    'Santander',
    'Huila',
    'Cesar',
    'Cundinamarca',
    'Tolima',
    'Norde de Santander',
    'Córdoba',
    'Valle del Cauca',
    'Magdalena',
    'Arauca',
    'Sucre',
    'Caldas',
    'Risaralda',
    'Distrito Capital de Bogotá',
    'Atlántico',
    'Quindio',
    'San Andrés, Providencia y Santa Catalina',
  ],
  croatia: [
    'Dubrovnik-Neretva',
    'Split-Dalmatia',
    'Primorje-Gorski Kotar',
    'Lika-Senj',
    'Zadar',
    'Sisak-Moslavina',
    'Osijek-Baranja',
    'Zagreb County',
    'Karlovac',
    'Šibenik-Knin',
    'Vukovar-Srijem',
    'Bjelovar-Bilogora',
    'Brod-Posavina',
    'Istria',
    'Virovitica-Podravina',
    'Požega-Slavonia',
    'Koprivnica-Križevci',
    'Varaždin',
    'Krapina-Zagorje',
    'Grad Zagreb',
  ],
  cuba: [
    'Camagüey',
    'Pinar del Río',
    'Ciego de Ávila',
    'Matanzas',
    'Villa Clara',
    'Holguín',
    'Granma',
    'Sancti Spíritus',
    'Las Tunas',
    'Santiago de Cuba',
    'Isla de la Juventud',
    'Guantánamo',
    'Cienfuegos',
    'Mayabeque',
    'Artemisa',
    'Ciudad de la Habana',
    // One Missing
  ],
  'czech-republic': [
    'Středočeský',
    'Jihočeský',
    'Jihomoravský',
    'Ústecký',
    'Plzeňský',
    'Moravskoslezský',
    'Olomoucký',
    'Vysočina',
    'Královéhradecký',
    'Pardubický',
    'Liberecký',
    'Karlovarský',
    'Praha',
  ],
  congo: [
    'Sangha',
    'Likouala',
    'Cuvette',
    'Niari',
    'Plateaux',
    'Pool',
    'Cuvette-Ouest',
    'Lékoumou',
    'Kouilou',
    'Bouenza',
    'Pointe-Noire',
    'Brazzaville',
  ],
  'dominican-republic': [
    'La Altagracia',
    'Azua',
    'Monte Plata',
    'Santiago',
    'San Juan',
    'La Vega',
    'Independencia',
    'Pedernales',
    'Elías Piña',
    'Puerto Plata',
    'Barahona',
    'Duarte',
    'El Seibo',
    'Hato Mayor',
    'Monte Cristi',
    'Samaná',
    'San Pedro de Macorís',
    'Santo Domingo',
    'María Trinidad Sánchez',
    'Espaillat',
    'San Cristóbal',
    'Bahoruco',
    'Santiago Rodríguez',
    'Monseñor Nouel',
    'Dajabón',
    'Sánchez Ramírez',
    'San José de Ocoa',
    'Peravia',
    'Valverde',
    'Hermanas Mirabal',
    'La Romana',
    'Distrito Nacional',
  ],
  'cayland-islands': ['Grand Cayman', 'CaymanBrac', 'Little Cayman'],
  cambodia: [
    'Koh Kong',
    'Preah Vihear',
    'Pursat',
    'Kampong Thom',
    'Stung Treng',
    'Kratié',
    'Battambang',
    'Mondul Kiri',
    'Ratana Kiri',
    'Siemreap',
    'Kampong Speu',
    'Banteay Meanchey',
    'Oddar Meanchey',
    'Tboung Khmum',
    'Kampong Cham',
    'Prey Veng',
    'Preah Sihanouk',
    'Kampong Chhnang',
    'Kandal',
    'Kampot',
    'Taakaev',
    'Svay Rieng',
    'Pailin',
    'Phnom Penh',
    'Kep',
  ],
  cameroon: [
    'East',
    'North',
    'Centre',
    'Adamaoua',
    'Far North',
    'South',
    'South-West',
    'Littoral',
    'Nord-West',
    'West',
  ],
  canada: [
    'Nunavut',
    'Northwest Territories',
    'Quebec',
    'Ontario',
    'British Columbia',
    'Northwest Territories',
    'Newfoundland and Labrador',
    'Yukon',
    'Manitoba',
    'Alberta',
    'Saskatchewan',
    'Nova Scotia',
    'New Brunswick',
    'Prince Edward Island',
  ],
  'central-african-republic': [
    'Haute-Kotto',
    'Haut-Mbomou',
    'Bamingui-Bangoran',
    'Mbomou',
    'Ouaka',
    'Ouham',
    'Vakaga',
    'Ombella-Mpoko',
    'Ouham-Pendé',
    'Sangha',
    'Haute-Sangha',
    'Nana-Mambéré',
    'Gribingui',
    'Lobaye',
    'Sangha',
  ],
  chile: [
    'Valparaíso',
    'Magallanes and Chilean Antarctica Región',
    'Aisén del General Carlos Ibañez del Campo',
    'Antofagasta',
    'Atacama',
    'Los Lagos',
    'Biobío',
    'Coquimbo',
    'Los Ríos',
    'Tarapacá',
    'Maule',
    'Los Ríos',
    'Región Metropolitana de Santiago',
    'Arica y Parinacota',
    'Libertador General Bernardo O Higgins',
    'Ñuble',
  ],
  china: [
    'Nei Mongol',
    'Xinjiang Uygur',
    'Xizang (Tibet)',
    'Gansu',
    'Heilongjiang',
    'Qinghai',
    'Sichuan',
    'Yunnan',
    'Jilin',
    'Shanxi',
    'Hebei',
    'Guangdong',
    'Guangxi Zhuang',
    'Liaoning',
    'Hubei',
    'Henan',
    'Shandong',
    'Hunan',
    'Jiangxi',
    'Guizhou',
    'shaanxi',
    'Anhui',
    'Jiangsu',
    'Fujian',
    'Chongqing',
    'Zhejiang',
    'Ningxia Hui',
    'Taiwan',
    'Hainan',
    'Beijing',
    'Tianjin',
    'Shanghai',
    'Yunnan',
  ],
  costarica: ['Puntarenas', 'Limón', 'Guanacaste', 'Alajuela', 'San José', 'Cartago', 'Heredia', 'Lake Arenal'],
  cyprus: ['Famagusta', 'Nicosia', 'Paphos', 'Larnaca', 'Limassol', 'Kyrenia', 'Dhekelia', 'Akrotiri'],
  'congo-dr': [
    'Tshopo',
    'Haut-Katanga',
    'Lualaba',
    'Tshuapa',
    'Maniema',
    'Mai-Ndombe',
    'Bas-Uélé',
    'Équateur',
    'Haut-Lomami',
    'Tanganyika',
    'Kwango',
    'Kasaï',
    'Haut-Uélé',
    'Sankuru',
    'Ituri',
    'Kwilu',
    'Mongala',
    'Lomami',
    'Nord-Ubangi',
    'Sud-Kivu',
    'Kasaï Central',
    'Sud-Ubangi',
    'Nord-Kivu',
    'Kongo Central',
    'Kinshasa City',
    'Kasaï-Oriental',
  ],
  taiwan: [
    'Taitung',
    'Hualien',
    'Kaohsiung City',
    'Kinmen',
    'New Taipei City',
    'Nantou',
    'Pingtung',
    'Yilan',
    'Taichung City',
    'Chiayi',
    'Tainan City',
    'Miaoli',
    'Taoyuan',
    'Lienchiang',
    'Hsinchu',
    'Penghu',
    'Yunlin',
    'Changhua',
    'Taipei City',
    'Hsinchu City',
    'Keelung City',
    'Chiayi City',
  ],
  togo: ['Plateaux', 'Centre', 'Kara', 'Savanes', 'Maritime'],
  'trinidad-and-tobago': [
    'Sangre Grande',
    'Rio Claro-Mayaro',
    'Siparia',
    'Couva-Tabaquite-Talparo',
    'Princes Town',
    'Tunapuna/Piarco',
    'San Juan-Laventille',
    'Western Tobago',
    'Penal-Debe',
    'Eastern Tobago',
    'Diego Martin',
    'Chaguanas',
    'Point Fortin',
    'San Fernando',
    'Port of Spain',
  ],
  tanzania: [
    'Morogoro',
    'Tabora',
    'Ruvuma',
    'Lindi',
    'Manyara',
    'Katavi',
    'Kigoma',
    'Singida',
    'Arusha',
    'Mbeya',
    'Dodoma',
    'Iringa',
    'Pwani',
    'Songwe',
    'Rukwa',
    'Tanga',
    'Geita',
    'Kagera',
    'Simiyu',
    'Njombe',
    'Mtwara',
    'Mwanza',
    'Mara',
    'Shinyanga',
    'Kilimanjaro',
    'Dar es Salaam',
    'Kusini Unguja',
    'Kusini Pemba',
    'Kaskazini Pemba',
    'Kaskazini Unguja',
    'Simiyu',
  ],
  tunisia: [
    'Tataouine',
    'Kébili',
    'Médenine',
    'Sfax',
    'Gabès',
    'Kassérine',
    'Tozeur',
    'Kairouan',
    'Gafsa',
    'Siliana',
    'Le Kef',
    'Béja',
    'Bizerte',
    'Jendouba',
    'Nabeul',
    'Zaghouan',
    'Sousse',
    'Mahdia',
    'Manouba',
    'Monastir',
    'Ben Arous',
    'Ariana',
    'Tunis',
  ],
  turkmenistan: ['Chardzhou', 'Balkan', 'Ahal', 'Mary', 'Tashauz'],
  eritrea: ['Debub', 'Debubawi Keyih Bahri', 'Gash Barka', 'Semenawi Keyih Bahri', 'Maekel', 'Anseba'],
  estonia: [
    'Pärnumaa',
    'Harjumaa',
    'Saaremaa',
    'Lääne-Virumaa',
    'Ida-Virumaa',
    'Viljandimaa',
    'Tartumaa',
    'Läänemaa',
    'Raplamaa',
    'Jõgevamaa',
    'Järvamaa',
    'Valgamaa',
    'Põlvamaa',
    'Võrumaa',
    'Hiiumaa',
  ],
  ethiopia: [
    'Somali',
    'Oromiya',
    'Amhara',
    'Southern Nations, Nationalities and Peoples',
    'Afar',
    'Benshangul-Gumaz',
    'Tigray',
    'Gambela Peoples',
    'Dire Dawa',
    'Addis Ababa',
    'Harari People',
  ],
  denmark: ['Midtjylland', 'Hovedstaden', 'Nordjylland', 'Syddanmark', 'Sjælland'],
  djibouti: ['Tadjourah', 'Dikhil', 'Obock', 'Arta', 'Ali Sabieh', 'Djibouti'],
  'timor-leste': [
    'Lautem',
    'Viqueque',
    'Cova Lima',
    'Manatuto',
    'Bobonaro',
    'Manufahi',
    'Baucau',
    'Dili',
    'Ambeno',
    'Ainaro',
    'Ermera',
    'Aileu',
  ],
  tajikistan: ['Gorno-Badakhshan', 'Sughd', 'nohiyahoi tobei jumhurí', 'Khatlon', 'Dushanbe'],
  thailand: [
    'Tak',
    'Krabi',
    'Chiang Mai',
    'Kanchanaburi',
    'Nakhon Ratchasima',
    'Mae Hong Son',
    'Lampang',
    'Surat Thani',
    'Ubon Ratchathani',
    'Udon Thani',
    'Phetchabun',
    'Khon Kaen',
    'Nakhon Sawan',
    'Chiang Rai',
    'Loei',
    'Nan',
    'Phitsanulok',
    'Buri Ram',
    'Songkhla',
    'Nakhon Si Thammarat',
    'Chaiyaphum',
    'Uttaradit',
    'Sakon Nakhon',
    'Prachuap Khiri Khan',
    'Phrae',
    'Chumphon',
    'Si Sa Ket',
    'Surin',
    'Roi Et',
    'Kamphaeng Phet',
    'Kalasin',
    'Suphan Buri',
    'Sa Kaeo',
    'Nakhon Phanom',
    'Uthai Thani',
    'Nong Khai',
    'Lop Buri',
    'Sukhothai',
    'Chachoengsao',
    'Chon Buri',
    'Phayao',
    'Yasothon',
    'Chanthaburi',
    'Prachin Buri',
    'Ranong',
    'Lamphun',
    'Maha Sarakham',
    'Yala',
    'Phetchaburi',
    'Satun',
    'Ratchaburi',
    'Phangnga',
    'Saraburi',
    'Trang',
    'Mukdahan',
    'Narathiwat',
    'Nong Bua Lam Phu',
    'Bueng Kan',
    'Trat',
    'Phichit',
    'Phatthalung',
    'Rayong',
    'Amnat Charoen',
    'Phra Nakhon Si Ayutthaya',
    'Nakhon Nayok',
    'Chai Nat',
    'Bangkok Metropolis',
    'Nakhon Pathom',
    'Pattani',
    'Pathum Thani',
    'Songkhla Lake',
    'Samut Prakan',
    'Samut Sakhon',
    'Sing Buri',
    'Ang Thong',
    'Nonthaburi',
    'Phuket',
    'Samut Songkhram',
    'Phatthaya',
  ],
  turkey: [
    'Konya',
    'Ankara',
    'Sivas',
    'Antalya',
    'Erzurum',
    'Balıkesir',
    'Mersin',
    'İzmir',
    'Şanlıurfa',
    'Muğla',
    'Kayseri',
    'Van',
    'Afyon',
    'Adana',
    'Yozgat',
    'Diyarbakır',
    'Manisa',
    'Erzincan',
    'Çanakkale',
    'Denizli',
    'Ağrı',
    'Malatya',
    'Eskişehir',
    'Kastamonu',
    'Çorum',
    'Tokat',
    'Kahramanmaraş',
    'Samsun',
    'Kütahya',
    'Bolu',
    'Bitlis',
    'Elazığ',
    'Bursa',
    'Kars',
    'Isparta',
    'Burdur',
    'Çankırı',
    'Muş',
    'Mardin',
    'Tekirdağ',
    'İstanbul',
    'Karaman',
    'Bingöl',
    'Aydin',
    'Aksaray',
    'Adıyaman',
    'Tunceli',
    'Artvin',
    'Edirne',
    'Gaziantep',
    'Şırnak',
    'Gümüşhane',
    'Hakkâri',
    'Kırşehir',
    'Giresun',
    'Niğde',
    'Amasya',
    'Sinop',
    'Ardahan',
    'Hatay',
    'Kırklareli',
    'Ordu',
    'Usak',
    'Nevşehir',
    'Siirt',
    'Rize',
    'Batman',
    'Kırıkkale',
    'Sakarya',
    'Trabzon',
    'Bilecik',
    'Iğdır',
    'Kocaeli',
    'Zonguldak',
    'Bayburt',
    'Karabük',
    'Osmaniye',
    'Bartın',
    'Düzce',
    'Kilis',
    'Yalova',
  ],
  ecuador: [
    'Galápagos',
    'Morona Santiago',
    'Pastaza',
    'Orellana',
    'Sucumbíos',
    'Manabí',
    'Guayas',
    'Esmeraldas',
    'Loja',
    'Zamora Chinchipe',
    'Napo',
    'Pichincha',
    'Azuay',
    'Los Ríos',
    'Imbabura',
    'Chimborazo',
    'Carchi',
    'Cotopaxi',
    'El Oro',
    'Santa Elena',
    'Santo Domingo de los Tsáchilas',
    'Cañar',
    'Bolivar',
    'Tungurahua',
  ],
  egypt: [
    'Al Wadi al Jadid',
    'Al Bahr al Ahmar',
    'Matruh',
    'Al Jizah',
    'Aswan',
    'Janub Sina',
    'Shamal Sina',
    'Al Minya',
    'Al Buhayrah',
    'As Suways',
    'Qina',
    'Bani Suwayf',
    'Al Isma iliyyah',
    'Al Fayyum',
    'al Qahira',
    'Ash Sharqīyah',
    'Suhaj',
    'Ad Daqahliyah',
    'Asyut',
    'Kafr ash Shaykh',
    'Al Iskandariyah',
    'Al Gharbiyah',
    'Dumyat',
    'Al Minufiyah',
    'Al Qalyubiyah',
    'Bur Sa`id',
    'Al Uqsur',
  ],
  'el-salvador': [
    'Chalatenango',
    'San Miguel',
    'Usulután',
    'Santa Ana',
    'La Libertad',
    'La Unión',
    'San Vicente',
    'Sonsonate',
    'San Salvador',
    'Ahuachapán',
    'La Paz',
    'Morazán',
    'Cuscatlán',
  ],
  'equatorial-guinea': [
    'Litoral',
    'Centro Sur',
    'Wele-Nzas',
    'Kié-Ntem',
    'Bioko Sur',
    'Bioko Norte',
    'Djibloho',
    'Annobón',
  ],
  'falkland-islands': ['Falkland Islands'],
  fiji: ['Eastern', 'Northern', 'Central', 'Western'],
  finland: [
    'Lapland',
    'Northern Ostrobothnia',
    'Kainuu',
    'North Karelia',
    'Central Finland',
    'Northern Savonia',
    'Southern Savonia',
    'Ostrobothnia',
    'Southern Ostrobothnia',
    'Uusimaa',
    'South Karelia',
    'Pirkanmaa',
    'Southwest Finland',
    'Satakunta',
    'Central Ostrobothnia',
    'Päijänne Tavastia',
    'Kymenlaakso',
    'Tavastia Proper',
    'Åland Islands',
  ],
  france: [
    'Nouvelle-Aquitaine',
    'Occitanie',
    'Auvergne-Rhône-Alpes',
    'Grand Est',
    'Bourgogne-Franche-Comté',
    'Centre-Val de Loire',
    'Pays de la Loire',
    "Provence-Alpes-Côte d'Azur",
    'Normandie',
    'Hauts-de-France',
    'Bretagne',
    'Île-de-France',
    'Corse',
  ],
  'french-southern-and-antarctic-lands': ['Archipel des Kerguelen'],
  gabon: [
    'Ogooué-Ivindo',
    'Wouleu-Ntem',
    'Ngounié',
    'Ogooué-Maritime',
    'Ogooué-Lolo',
    'Haut-Ogooué',
    'Nyanga',
    'Moyen-Ogooué',
    'Estuaire',
],
gambia: [
  'Central River',
  'North Bank',
  'West Coast',
  'Lower River',
  'Upper River',
  'Banjul',
],
georgia: [
  'Kakheti',
  'Abkhazia',
  'Samegrelo-Zemo Svaneti',
  'Samtskhe-Javakheti',
  'Mtskheta-Mtianeti',
  'Imereti',
  'Kvemo Kartli',
  'Shida Kartli',
  'Racha-Lechkhumi-Kvemo Svaneti',
  'Ajaria',
  'Guria',
  'Tbilisi',
],
germany: [
  'Bavaria',
  'Lower Saxony',
  'North Rhine-Westphalia',
  'Brandenburg',
  'Baden-Württemberg',
  'Mecklenburg-Western Pomerania',
  'Hesse',
  'Sachsen-Anhalt',
  'Schleswig-Holstein',
  'Saxony',
  'Rhineland-Palatinate',
  'Thuringia',
  'Saarland',
  'Bremen',
  'Berlin',
  'Hamburg',
],
ghana: [
  'Savannah',
  'Northern',
  'Ashanti',
  'Bono East',
  'Western',
  'Bono',
  'Central',
  'Eastern',
  'Upper West',
  'Western North',
  'Oti',
  'Volta',
  'North East',
  'Upper East',
  'Ahafo',
  'Greater Accra',
],
greece: [
  'Southern Aegean',
  'Northern Aegean',
  'Central Greece',
  'East Macedonia and Thrace',
  'Thessaly',
  'Central Macedonia',
  'Peloponnese',
  'Western Greece',
  'Ionian Islands',
  'Attica',
  'Crete',
  'Epirus',
  'West Macedonia',
  'Mount Athos',
],
greenland: [
  'Northeast Greenland National Park',
  'Avannaata',
  'Sermersooq',
  'Qeqqata',
  'Qeqertalik',
  'Kujalleq'
],
grenada: [
  'Saint Patrick',
  'Southern Grenadine Islands',
  'Saint George',
  'Saint Andrew',
  'Saint David',
  'Saint John',
  'Saint Mark',
],
guatemala: [
  'Petén',
  'Alta Verapaz',
  'Izabal',
  'Quiché',
  'Huehuetenango',
  'Jutiapa',
  'San Marcos',
  'Escuintla',
  'Quezaltenango',
  'Zacapa',
  'Santa Rosa',
  'Suchitepéquez',
  'Baja Verapaz',
  'Retalhuleu',
  'Guatemala',
  'Chiquimula',
  'El Progreso',
  'Chimaltenango',
  'Jalapa',
  'Sololá',
  'Totonicapán',
  'Sacatepéquez',
],
'guinea-bissau': [
  'Gabú',
  'Cacheu',
  'Bafatá',
  'Tombali',
  'Bolama',
  'Oio',
  'Quinara',
  'Biombo',
  'Bissau',
],
guinea: [
  'Kankan',
  'Nzérékoré',
  'Boké',
  'Faranah',
  'Kindia',
  'Labé',
  'Mamou',
  'Conakry',
],
guyana: [
  'Mahaica-Berbice',
  'Upper Demerara-Berbice',
  'Pomeroon-Supenaam',
  'Potaro-Siparuni',
  'Barima-Waini',
  'Upper Takutu-Upper Essequibo',
  'Cuyuni-Mazaruni',
  'Demerara-Mahaica',
  'Essequibo Islands-West Demerara',
  'East Berbice-Corentyne',
],
haiti: [
  'Ouest',
  'LArtibonite',
  'Sud',
  'Centre',
  'Sud-Est',
  'Nord',
  'Nord-Ouest',
  'Nippes',
  'GrandAnse',
  'Nord-Est',
],
honduras: [
  'Olancho',
  'Gracias a Dios',
  'El Paraíso',
  'Colón',
  'Yoro',
  'Francisco Morazán',
  'Comayagua',
  'Cortés',
  'Atlántida',
  'Santa Bárbara',
  'Lempira',
  'Choluteca',
  'Intibucá',
  'Islas de la Bahía',
  'Copán',
  'La Paz',
  'Ocotepeque',
  'Valle',
],
'hong-kong': [
  'Islands',
  'Tai Po',
  'Sai Kung',
  'Yuen Long',
  'North',
  'Tsuen Wan',
  'Tuen Mun',
  'Southern',
  'Sha Tin',
  'Kwai Tsing',
  'Eastern',
  'Kowloon City',
  'Kwun Tong',
  'Central and Western',
  'Sham Shui Po',
  'Wan Chai',
  'Wong Tai Sin',
  'Yau Tsim Mong',
],
hungary: [
  'Borsod-Abaúji-Zemplén',
  'Bács-Kiskun',
  'Pest',
  'Szalbolcs-Szatmár-Bereg',
  'Somogy',
  'Hajdú-Bihar',
  'Jász-Nagykun-Szolnok',
  'Békés',
  'Győr-Moson-Sopron',
  'Heves',
  'Vas',
  'Veszprém',
  'Baranya',
  'Fejér',
  'Csongrád',
  'Tolna',
  'Nógrád',
  'Komárom-Esztergom',
  'Budapest',
],
iceland: [
  'Norðurland eystra',
  'Austurland',
  'Suðurland',
  'Vestfirðir',
  'Vesturland',
  'Norðurland vestra',
  'Vatnajökull',
  'Höfuðborgarsvæði',
  'Langjökull',
  'Suðurnes',
  'Hofsjökull',
  'Mýrdalsjökull',
  'Drangajökull',
  'Eyjafjallajökull',
  'Tungnafellsjökull',
  'Eiríksjökull',
  'Snæfellsjökull',
  'Þórisjökull',
],
india: [
  'Rajasthan',
  'Maharashtra',
  'Andhra Pradesh',
  'Madhya Pradesh',
  'Uttar Pradesh',
  'Jammu and Kashmir',
  'Karnataka',
  'Odisha',
  'Gujarat',
  'Chhattisgarh',
  'Assam',
  'West Bengal',
  'Tamil Nadu',
  'Telangana',
  'Arunachal Pradesh',
  'Jharkhand',
  'Bihar',
  'Kerala',
  'Andaman and Nicobar Islands',
  'Haryana',
  'Himachal Pradesh',
  'Uttarakhand',
  'Punjab',
  'Nagaland',
  'Meghalaya',
  'Mizoram',
  'Manipur',
  'Tripura',
  'Sikkim',
  'Goa',
  'Delhi',
  'Daman and Diu',
  'Dadra and Nagar Haveli',
  'Chandigarh',
],
indonesia: [
  'Papua',
  'Maluku',
  'Kalimantan Barat',
  'Kalimantan Timur',
  'Sarawak',
  'Kepulauan Riau',
  'Papua Barat',
  'Maluku Utara',
  'Kalimantan Tengah',
  'Sulawesi Tengah',
  'Nusa Tenggara Timur',
  'Sumatera Utara',
  'Sulawesi Utara',
  'Jawa Timur',
  'Riau',
  'Sumatera Barat',
  'Jambi',
  'Sabah',
  'Sulawesi Selatan',
  'Aceh',
  'Kalimantan Utara',
  'Bengkulu',
  'Sulawesi Tenggara',
  'Kepulauan Bangka Belitung',
  'Kalimantan Selatan',
  'Jawa Tengah',
  'Lampung',
  'Jawa Barat',
  'Timor-Leste',
  'Nusa Tenggara Barat',
  'Sulawesi Barat',
  'Banten',
  'Gorontalo',
  'Brunei Darussalam',
  'Bali',
  'Yogyakarta',
  'Jakarta Raya',
],
};

export default fields;
