const fields = {
  nigeria: [
    'abia',
    'abuja',
    'adamawa',
    'akwa ibom',
    'anambra',
    'bauchi',
    'bayelsa',
    'benue',
    'borno',
    'cross river',
    'delta',
    'ebonyi',
    'edo',
    'ekiti',
    'enugu',
    'gombe',
    'imo',
    'jigawa',
    'kaduna',
    'kano',
    'katsina',
    'kebbi',
    'kogi',
    'kwara',
    'lagos',
    'nasarawa',
    'niger',
    'ogun',
    'ondo',
    'osun',
    'oyo',
    'plateau',
    'rivers',
    'sokoto',
    'taraba',
    'yobe',
    'zamfara',
  ],
  europe: [
    'albania',
    'andorra',
    'armenia',
    'austria',
    'belarus',
    'belgium',
    'bosnia and herzegovina',
    'bulgaria',
    'croatia',
    'cyprus',
    'czech republic',
    'denmark',
    'estonia',
    'finland',
    'france',
    'georgia',
    'germany',
    'greece',
    'hungary',
    'iceland',
    'ireland',
    'italy',
    'kosovo',
    'latvia',
    'liechtenstein',
    'lithuania',
    'luxembourg',
    'macedonia',
    'moldova',
    'montenegro',
    'netherlands',
    'norway',
    'poland',
    'portugal',
    'romania',
    'serbia',
    'slovakia',
    'slovenia',
    'spain',
    'sweden',
    'switzerland',
    'turkey',
    'ukraine',
    'united kingdom',
  ],
  africa: [
    'algeria',
    'angola',
    'benin',
    'botswana',
    'burkina faso',
    'burundi',
    'cameroon',
    'central african republic',
    'chad',
    'congo',
    'congo republic',
    'cote de ivoire',
    'djibouti',
    'egypt',
    'equatorial guinea',
    'eritrea',
    'ethiopia',
    'gabon',
    'gambia',
    'ghana',
    'guinea',
    'guinea bissau',
    'kenya',
    'lesotho',
    'liberia',
    'libya',
    'madagascar',
    'malawi',
    'mali',
    'mauritania',
    'morocco',
    'mozambique',
    'namibia',
    'niger',
    'nigeria',
    'rwanda',
    'senegal',
    'sierra leone',
    'somalia',
    'south africa',
    'south sudan',
    'sudan',
    'swaziland',
    'tanzania',
    'togo',
    'tunisia',
    'uganda',
    'west sahara',
    'zambia',
    'zimbabwe',
  ],
  'north-america': [
    'alabama',
    'alaska',
    'alberta',
    'arizona',
    'arkansas',
    'british columbia',
    'california',
    'colorado',
    'connecticut',
    'delaware',
    'district of columbia',
    'florida',
    'georgia',
    'hawaii',
    'idaho',
    'illinois',
    'indiana',
    'iowa',
    'kansas',
    'kentucky',
    'louisiana',
    'maine',
    'manitoba',
    'maryland',
    'massachusetts',
    'mexico',
    'michigan',
    'minnesota',
    'mississippi',
    'missouri',
    'montana',
    'nebraska',
    'nevada',
    'new brunswick',
    'new hampshire',
    'new jersey',
    'new mexico',
    'new york',
    'newfoundland labrador',
    'north carolina',
    'north dakota',
    'northwest territories',
    'nova scotia',
    'nunavut',
    'ohio',
    'oklahoma',
    'ontario',
    'oregon',
    'pennsylvania',
    'prince edward island',
    'quebec',
    'rhode island',
    'saskatchewan',
    'south carolina',
    'south dakota',
    'tennessee',
    'texas',
    'utah',
    'vermont',
    'virginia',
    'washington',
    'west virginia',
    'wisconsin',
    'wyoming',
    'yukon',
  ],
};

export default fields;
