const fields = {
  nigeria: [
    'abia',
    'abuja',
    'adamawa',
    'akwa ibom',
    'anambra',
    'bauchi',
    'bayelsa',
    'benue',
    'borno',
    'cross river',
    'delta',
    'ebonyi',
    'edo',
    'ekiti',
    'enugu',
    'gombe',
    'imo',
    'jigawa',
    'kaduna',
    'kano',
    'katsina',
    'kebbi',
    'kogi',
    'kwara',
    'lagos',
    'nasarawa',
    'niger',
    'ogun',
    'ondo',
    'osun',
    'oyo',
    'plateau',
    'rivers',
    'sokoto',
    'taraba',
    'yobe',
    'zamfara',
  ],
  europe: [
    'Russia',
    'Norway',
    'Spain',
    'Sweden',
    'Ukraine',
    'France',
    'Italy',
    'Turkey',
    'Finland',
    'United Kingdom',
    'Germany',
    'Svalbard and Jan Mayen',
    'Poland',
    'Belarus',
    'Greece',
    'Romania',
    'Iceland',
    'Croatia',
    'Austria',
    'Azerbaijan',
    'Hungary',
    'Bulgaria',
    'Latvia',
    'Ireland',
    'Portugal',
    'Georgia',
    'Serbia',
    'Czechia',
    'Lithuania',
    'Estonia',
    'Denmark',
    'Slovakia',
    'Netherlands',
    'Bosnia and Herzegovina',
    'Moldova',
    'Switzerland',
    'Belgium',
    'Armenia',
    'Albania',
    'Slovenia',
    'North Macedonia',
    'Montenegro',
    'Cyprus',
    'Kosovo',
    'Luxembourg',
    // 'Malta',
    // 'Vatican city'
  ],
  africa: [
    'algeria',
    'angola',
    'benin',
    'botswana',
    'burkina faso',
    'burundi',
    'cameroon',
    'central african republic',
    'chad',
    'congo',
    'congo republic',
    'cote de ivoire',
    'djibouti',
    'egypt',
    'equatorial guinea',
    'eritrea',
    'ethiopia',
    'gabon',
    'gambia',
    'ghana',
    'guinea',
    'guinea bissau',
    'kenya',
    'lesotho',
    'liberia',
    'libya',
    'madagascar',
    'malawi',
    'mali',
    'mauritania',
    'morocco',
    'mozambique',
    'namibia',
    'niger',
    'nigeria',
    'rwanda',
    'senegal',
    'sierra leone',
    'somalia',
    'south africa',
    'south sudan',
    'sudan',
    'swaziland',
    'tanzania',
    'togo',
    'tunisia',
    'uganda',
    'west sahara',
    'zambia',
    'zimbabwe',
  ],
  'north-america': [
    'United States',
    'Canada',
    'Greenland',
    'Mexico',
    'Cuba',
    'Nicaragua',
    'Honduras',
    'Guatemala',
    'Panama',
    'Costa Rica',
    'Dominican Republic',
    'Haiti',
    'Belize',
    'El Salvador',
    'Jamaica',
    'Puerto Rica',
  ],
  world: [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo (Congo-Brazzaville)',
    'Congo (Congo-Kinshasa)',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'East Timor (Timor-Leste)',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea, North (North Korea)',
    'Korea, South (South Korea)',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar (Burma)',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
  ],
  asia: [
    'Afghanistan',
    'Armenia',
    'Azerbaijan',
    'Bahrain',
    'Bangladesh',
    'Bhutan',
    'Brunei',
    'Cambodia',
    'China',
    'Cyprus',
    'Georgia',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Israel',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Lebanon',
    'Malaysia',
    'Maldives',
    'Mongolia',
    'Myanmar (Burma)',
    'Nepal',
    'North Korea',
    'Oman',
    'Pakistan',
    'Palestine',
    'Philippines',
    'Qatar',
    'Russia',
    'Saudi Arabia',
    'Singapore',
    'South Korea',
    'Sri Lanka',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Thailand',
    'Timor Leste',
    'Turkey',
    'Turkmenistan',
    'United Arab Emirates',
    'Uzbekistan',
    'Vietnam',
  ],
  'south-america': [
    'Brazil',
    'Argentina',
    'Chile',
    'Peru',
    'Colombia',
    'Bolivia',
    'Venezuela',
    'Paraguay',
    'Ecuador',
    'Guyana',
    'Uruguay',
    'Suriname',
    'French Guiana',
    'Falkland Islands',
  ],
  algeria: [
    'Tamanghasset',
    'Adrar',
    'Illizi',
    'Ouargla',
    'Béchar',
    'Tindouf',
    'Ghardaïa',
    'El Bayadh',
    'El Oued',
    'Djelfa',
    'Laghouat',
    'Biskra',
    'Naama',
    "M'Sila",
    'Tiaret',
    'Batna',
    'Tébessa',
    'Sidi Bel Abbès',
    'Tlemcen',
    'Khenchela',
    'Médéa',
    'Oum el Bouaghi',
    'Sétif',
    'Mascara',
    'Saïda',
    'Relizane',
    'Bouira',
    'Skikda',
    'Béjaïa',
    'Bordj Bou Arréridj',
    'Souk Ahras',
    'Chlef',
    'Aïn Defla',
    'Guelma',
    'Mila',
    'Aïn Témouchent',
    'Mostaganem',
    'Oran',
    'El Tarf',
    'Tissemsilt',
    'Jijel',
    'Tizi Ouzou',
    'Constantine',
    'Tipaza',
    'Boumerdès',
    'Blida',
    'Annaba',
    'Alger',
  ],
  angola: [
    'Moxico',
    'Cuando Cubango',
    'Lunda Norte',
    'Malanje',
    'Bié',
    'Lunda Sul',
    'Huíla',
    'Cunene',
    'Uíge',
    'Cuanza Sul',
    'Namibe',
    'Benguela',
    'Zaire',
    'Bengo',
    'Huambo',
    'Cuanza Norte',
    'Cabinda',
    'Luanda',
  ],
  albania: [
    'Vlorë',
    'Shkodër',
    'Korçë',
    'Elbasan',
    'Gjirokastër',
    'Kukës',
    'Dibër',
    'Tiranë',
    'Lezhë',
    'Fier',
    'Berat',
    'Durrës',
  ],
  oceanic: [
    'Australia',
    'Indonesia',
    'New Zealand',
    'Papua New Guinea',
    'New Caledonia',
    'Fiji',
    'Solomon Islands',
    'Timor-Leste',
    'Vanuatu',
  ],
  'nigeria-regions': ['South West', 'South South', 'South East', 'North West', 'North East', 'North Central'],
  afghanistan: [
    'Badakhshan',
    'Hirat',
    'Hilmand',
    'Kandahar',
    'Farah',
    'Ghor',
    'Nimroz',
    'Ghazni',
    'Faryab',
    'Badghis',
    'Balkh',
    'Baghlan',
    'Paktika',
    'Bamyan',
    'Sari Pul',
    'Zabul',
    'Uruzgan',
    'Jawzjan',
    'Samangan',
    'Wardak',
    'Uruzgan',
    'Nuristan',
    'Nangarhar',
    'Kunduz',
    'Parwan',
    'Paktya',
    'Kunar',
    'Logar',
    'Khost',
    'Kabul',
    'Laghman',
    'Kapisa',
  ],
  austria: [
    'Lower Austria',
    'Styria',
    'Tyrol',
    'Upper Austria',
    'Salzburg',
    'Carinthia',
    'Burgenland',
    'Vorarlberg',
    'Vienna',
  ],
  argentina: [
    'Buenos Aires',
    'Santa Cruz',
    'Río Negro',
    'Chubut',
    'Salta',
    'Santa Fe',
    'Mendoza',
    'Cordoba',
    'La Pampa',
    'Formosa',
    'Catamarca',
    'Chaco',
    'La Rioja',
    'Neuquén',
    'Santiago del Estero',
    'San Juan',
    'Corrientes',
    'Entre Ríos',
    'Tierra del Fuego',
    'San Luis',
    'Jujuy',
    'Misiones',
    'Tucumán',
    'Ciudad de Buenos Aires', // this is not showing on the map
  ],
  azerbaijan: [
    'Baki',
    'Abseron',
    'Kalbajar',
    'Şəki',
    'Neftçala',
    'Quba',
    'Haciqabul',
    'Tovuz',
    'Lənkəran',
    'Goranboy',
    'Qusar',
    'Laçın',
    'Ismayilli',
    'Sabirabad',
    'Aghjabadi',
    'Qax',
    'Imisli',
    'Xizi',
    'Salyan',
    'Samux',
    'Xocavənd',
    'Zaqatala',
    'Bilasuvar',
    'Shamkir',
    'Kurdamir',
    'Xaçmaz',
    'Agstafa',
    'Qabala',
    'Yevlax',
    'Agsu',
    'Qobustan',
    'Samaxi',
    'Babek',
    'Gədəbəy',
    'Cəlilabad',
    'Beylagan',
    'Sabran',
    'Tartar',
    'Agdam',
    'Göygöl',
    'Füzuli',
    'Agdas',
    'Lerik',
    'Oguz',
    'Culfa',
    'Ordubad',
    'Cəbrayıl',
    'Barda',
    'Sharur',
    'Balakan',
    'Khojali',
    'Saatli',
    'Siazan',
    'Yardimli',
    'Zardab',
    'Qubadli',
    'Dashkasan',
    'Zangilan',
    'Sahbuz',
    'Masalli',
    'Qazax',
    'Ucar',
    'Göyçay',
    'Astara',
    'Kangarli',
    'Susa',
    'Sadarak',
    'Sumqayit',
    'Ganja',
    'Mingachevir',
    'Shirvan City',
    'Naxçıvan',
    'Şəki City',
    "Gegark'unik'",
    'Yevlax City',
    'Naftalan City',
    'Lənkəran City',
  ],
  benin: [
    'Borgou',
    'Alibori',
    'Atakora',
    'Collines',
    'Donga',
    'Zou',
    'Plateau',
    'Kouffo',
    'Atlantique',
    'Mono',
    'Ouémé',
    'Littoral',
  ],
  bangladesh: ['Chittagong', 'Dhaka', 'Khulna', 'Rangpur', 'Rajshahi', 'Sylhet', 'Mymensingh'],
  belarus: ['Vitsyebsk', 'Homyel', 'Minsk', 'Brest', 'Mahilyow', 'Hrodna', 'Minsk City'],
  bermuda: [
    'St.George',
    'Sandys',
    'Hamilton',
    'Southampton',
    'Warwick',
    'Paget',
    'Smiths',
    'Devonshire',
    'Hamilton',
    'St.George-Town',
  ],
  botswana: ['Central', 'Kgalagadi', 'Ghanzi', 'North West', 'Kweneng', 'Southern', 'Kgatleng', 'North East', 'Chobe'],
  bahrain: ['Al Janūbīyah', 'Ash Shamālīyah', 'Al ‘Āşimah', 'Al Muḩarraq'],
  bulgaria: [
    'Sofia-Grad',
    'Burgas',
    'Haskovo',
    'Plovdiv',
    'Blagoevgrad',
    'Dobrich',
    'Veliko Tarnovo',
    'Stara Zagora',
    'Vratsa',
    'Kyustendil',
    'Ruse',
    'Pazardzhik',
    'Lovech',
    'Varna',
    'Shumen',
    'Pleven',
    'Sliven',
    'Smolyan',
    'Yambol',
    'Montana',
    'Kardzhali',
    'Silistra',
    'Razgrad',
    'Vidin',
    'Targovishte',
    'Pernik',
    'Gabrovo',
    'Sofia',
  ],
  burkinafaso: [
    'Est',
    'Sahel',
    'Boucle du Mouhoun',
    'Hauts-Bassins',
    'Centre-Ouest',
    'Sud-Ouest',
    'Cascades',
    'Centre-Nord',
    'Centre-Est',
    'Nord',
    'Plateau-Central',
    'Centre-Sud',
    'Centre',
  ],
  burundi: [
    'Muyinga',
    'Ruyigi',
    'Makamba',
    'Gitega',
    'Rutana',
    'Cankuzo',
    'Bururi',
    'Cibitoke',
    'Ngozi',
    'Kirundo',
    'Karuzi',
    'Kayanza',
    'Rumonge',
    'Bujumbura Rural',
    'Bubanza',
    'Mwaro',
    'Muramvya',
    'Bujumbura Mairie',
  ],
  armenia: [
    "Gegark'unik",
    "Syunik'",
    'Loṙi',
    'Aragac̣otn',
    'Tavuš',
    'Širak',
    "Kotayk'",
    'Ararat',
    'Vayoć Jor',
    'Armavir',
    'Erevan',
  ],
  australia: [
    'Western Australia',
    'Queensland',
    'South Australia',
    'Northern Territory',
    'New South Wales',
    'Victoria',
    'Tasmania',
  ],
  belgium: [
    'Hainaut',
    'Luxembourg',
    'Liège',
    'Namur',
    'West Flanders',
    'East Flanders',
    'Limburg',
    'Antwerpen',
    'Flemish Brabant',
    'Walloon Brabant',
    'Brussels Capital Region',
  ],
  belize: ['Belize', 'Orange Walk', 'Cayo', 'Toledo', 'Corozal', 'Stann Creek'],
  bhutan: [
    'Wangdue Phodrang',
    'Gasa',
    'Lhuentse',
    'Sarpang',
    'Thimphu',
    'Bumthang',
    'Zhemgang',
    'Monggar',
    'Trashigang',
    'Samdrup Jongkhar',
    'Chhukha',
    'Trongsa',
    'Samtse',
    'Haa',
    'Trashi Yangtse',
    'Dagana',
    'Paro',
    'Pemagatshel',
    'Punakha',
  ],
  bolivia: ['Santa Cruz', 'El Beni', 'Potosí', 'La Paz', 'Pando', 'Chuquisaca', 'Cochabamba', 'Oruro', 'Tarija'],
  'bosnia-and-aerzegovina': ['Republika Srpska', 'Federacija Bosne i Hercegovine', 'Brčko distrikt'],
  brazil: [
    'Amazonas',
    'Pará',
    'Mato Grosso',
    'Minas Gerais',
    'Bahia',
    'Maranhão',
    'Rio Grande do Sul',
    'Goiás',
    'Mato Grosso do Sul',
    'São Paulo',
    'Piauí',
    'Tocantins',
    'Rondônia',
    'Roraima',
    'Acre',
    'Paraná',
    'Amapá',
    'Ceará',
    'Santa Catarina',
    'Pernambuco',
    'Rio de Janeiro',
    'Paraíba',
    'Rio Grande do Norte',
    'Espírito Santo',
    'Alagoas',
    'Sergipe',
  ],
  'brunei-darussalam': ['Belait', 'Tutong', 'Temburong', 'Brunei-Mua'],
  bahamas: [
    'North Andros',
    'Inagua',
    'Acklins',
    'Long Island',
    'Crooked Island and Long Cay',
    'South Andros',
    'Black Point',
    'Cat Island',
    'South Abaco',
    'Central Andros',
    'West Grand Bahama',
    'Central Abaco',
    'North Abaco',
    'Exuma',
    'East Grand Bahama',
    'North Eleuthera',
    'Mangrove Cay',
    'Mayaguana',
    'Central Eleuthera',
    'South Eleuthera',
    'Rum Cay',
    'New Providence',
    'San Salvador',
    "Moore's Island",
    'Berry Islands',
    'Spanish Wells',
    'Hope Town',
    'Ragged Island',
    'City of Freeport',
    'Harbour Island',
    'Grand Cay',
  ],
};

export default fields;
