import {
  TbBattery,
  TbBell,
  TbBookmark,
  TbBriefcase,
  TbCalendar,
  TbCamera,
  TbCheck,
  TbCircle,
  TbClock,
  TbCloud,
  TbCreditCard,
  TbDownload,
  TbEdit,
  TbEye,
  TbEyeOff,
  TbFilter,
  TbFlag,
  TbHeart,
  TbHome,
  TbLink,
  TbLock,
  TbMail,
  TbMap,
  TbMenu,
  TbMicrophone,
  TbMinus,
  TbMoon,
  TbMusic,
  TbPhone,
  TbPlus,
  TbPrinter,
  TbRefresh,
  TbSearch,
  TbSettings,
  TbShare,
  TbShoppingCart,
  TbSquare,
  TbStar,
  TbSun,
  TbTag,
  TbTrash,
  TbTriangle,
  TbUmbrella,
  TbUpload,
  TbUser,
  TbVideo,
  TbVolume,
  TbWifi,
  TbX,
} from 'react-icons/tb';

export default [
  { name: 'heart', icon: TbHeart, keywords: ['heart', 'love', 'like'], type: 'react-icons' },
  { name: 'user', icon: TbUser, keywords: ['user', 'person', 'profile'], type: 'react-icons' },
  { name: 'home', icon: TbHome, keywords: ['home', 'house', 'residence'], type: 'react-icons' },
  { name: 'search', icon: TbSearch, keywords: ['search', 'find', 'magnify'], type: 'react-icons' },
  { name: 'settings', icon: TbSettings, keywords: ['settings', 'gear', 'preferences'], type: 'react-icons' },
  { name: 'bell', icon: TbBell, keywords: ['bell', 'notification', 'alert'], type: 'react-icons' },
  { name: 'mail', icon: TbMail, keywords: ['mail', 'email', 'message'], type: 'react-icons' },
  { name: 'phone', icon: TbPhone, keywords: ['phone', 'call', 'telephone'], type: 'react-icons' },
  { name: 'camera', icon: TbCamera, keywords: ['camera', 'photo', 'picture'], type: 'react-icons' },
  { name: 'calendar', icon: TbCalendar, keywords: ['calendar', 'date', 'schedule'], type: 'react-icons' },
  { name: 'clock', icon: TbClock, keywords: ['clock', 'time', 'watch'], type: 'react-icons' },
  { name: 'map', icon: TbMap, keywords: ['map', 'location', 'navigation'], type: 'react-icons' },
  { name: 'star', icon: TbStar, keywords: ['star', 'favorite', 'rating'], type: 'react-icons' },
  { name: 'bookmark', icon: TbBookmark, keywords: ['bookmark', 'save', 'favorite'], type: 'react-icons' },
  { name: 'trash', icon: TbTrash, keywords: ['trash', 'delete', 'remove'], type: 'react-icons' },
  { name: 'edit', icon: TbEdit, keywords: ['edit', 'pencil', 'modify'], type: 'react-icons' },
  { name: 'share', icon: TbShare, keywords: ['share', 'send', 'social'], type: 'react-icons' },
  { name: 'download', icon: TbDownload, keywords: ['download', 'save', 'arrow-down'], type: 'react-icons' },
  { name: 'upload', icon: TbUpload, keywords: ['upload', 'send', 'arrow-up'], type: 'react-icons' },
  { name: 'lock', icon: TbLock, keywords: ['lock', 'security', 'private'], type: 'react-icons' },
  { name: 'eye', icon: TbEye, keywords: ['eye', 'view', 'visible'], type: 'react-icons' },
  { name: 'eye-off', icon: TbEyeOff, keywords: ['eye-off', 'hide', 'invisible'], type: 'react-icons' },
  { name: 'plus', icon: TbPlus, keywords: ['plus', 'add', 'new'], type: 'react-icons' },
  { name: 'minus', icon: TbMinus, keywords: ['minus', 'remove', 'subtract'], type: 'react-icons' },
  { name: 'x', icon: TbX, keywords: ['x', 'close', 'cancel'], type: 'react-icons' },
  { name: 'check', icon: TbCheck, keywords: ['check', 'done', 'complete'], type: 'react-icons' },
  { name: 'circle', icon: TbCircle, keywords: ['circle', 'round', 'shape'], type: 'react-icons' },
  { name: 'square', icon: TbSquare, keywords: ['square', 'box', 'shape'], type: 'react-icons' },
  { name: 'triangle', icon: TbTriangle, keywords: ['triangle', 'shape', 'warning'], type: 'react-icons' },
  { name: 'menu', icon: TbMenu, keywords: ['menu', 'hamburger', 'list'], type: 'react-icons' },
  { name: 'refresh', icon: TbRefresh, keywords: ['refresh', 'reload', 'update'], type: 'react-icons' },
  { name: 'filter', icon: TbFilter, keywords: ['filter', 'funnel', 'sort'], type: 'react-icons' },
  { name: 'link', icon: TbLink, keywords: ['link', 'chain', 'url'], type: 'react-icons' },
  { name: 'cloud', icon: TbCloud, keywords: ['cloud', 'storage', 'weather'], type: 'react-icons' },
  { name: 'sun', icon: TbSun, keywords: ['sun', 'day', 'light'], type: 'react-icons' },
  { name: 'moon', icon: TbMoon, keywords: ['moon', 'night', 'dark'], type: 'react-icons' },
  { name: 'umbrella', icon: TbUmbrella, keywords: ['umbrella', 'rain', 'protection'], type: 'react-icons' },
  { name: 'flag', icon: TbFlag, keywords: ['flag', 'mark', 'report'], type: 'react-icons' },
  { name: 'tag', icon: TbTag, keywords: ['tag', 'label', 'category'], type: 'react-icons' },
  { name: 'music', icon: TbMusic, keywords: ['music', 'note', 'sound'], type: 'react-icons' },
  { name: 'video', icon: TbVideo, keywords: ['video', 'movie', 'film'], type: 'react-icons' },
  { name: 'microphone', icon: TbMicrophone, keywords: ['microphone', 'audio', 'record'], type: 'react-icons' },
  { name: 'volume', icon: TbVolume, keywords: ['volume', 'sound', 'speaker'], type: 'react-icons' },
  { name: 'wifi', icon: TbWifi, keywords: ['wifi', 'wireless', 'internet'], type: 'react-icons' },
  { name: 'battery', icon: TbBattery, keywords: ['battery', 'power', 'energy'], type: 'react-icons' },
  { name: 'briefcase', icon: TbBriefcase, keywords: ['briefcase', 'work', 'job'], type: 'react-icons' },
  { name: 'shopping-cart', icon: TbShoppingCart, keywords: ['shopping-cart', 'buy', 'purchase'], type: 'react-icons' },
  { name: 'credit-card', icon: TbCreditCard, keywords: ['credit-card', 'payment', 'money'], type: 'react-icons' },
  { name: 'printer', icon: TbPrinter, keywords: ['printer', 'print', 'document'], type: 'react-icons' },
];
